package com.weaponsregistration.purchase.model;
public enum ProcurementStatus {
    DRAFT, PLANNING, UNDER_REVIEW, AUTHORIZED, PUBLISHED,
    PROPOSAL_PHASE, QUALIFICATION_PHASE, JUDGMENT_PHASE,
    APPEAL_PHASE, AWARDED, HOMOLOGATED, CONTRACTED, CANCELLED, FAILED
}