package com.weaponsregistration.purchase.model;
public enum ReceiptStatus {
    DRAFT, UNDER_INSPECTION, PROVISIONALLY_RECEIVED, PARTIALLY_ACCEPTED,
    ACCEPTED, PARTIALLY_REJECTED, REJECTED, DEFINITIVELY_RECEIVED, CANCELLED
}