"use client";
import * as React from "react";
import axios from "axios";
import { Button } from "@primereact/ui/button";
import { Layout } from "components/layout";
import { Message } from "components/common/message";
import { useSession } from "components/auth/session-provider";
import { ReferenceField } from "components/erp/shared/record-workspace";
import { createErpService } from "api/services/erp.service";
import { donationService as api } from "api/services/donation.service";
import type { ErpField,ErpValue } from "api/models/erp";
import type { Donation,DonationPage,DonationRequest,DonationStockOption } from "api/models/erp/donation";
import styles from "components/erp/shared/workspace.module.css";
const core=createErpService("core");
const ref=(name:string,label:string,resource:string,required=true):ErpField=>({name,label,type:"reference",required,reference:resource,choices:[]});
const errorText=(error:unknown)=>axios.isAxiosError(error)&&typeof error.response?.data?.detail==="string"?error.response.data.detail:"Unable to complete the request. Check the API connection and try again.";
type Selected=DonationStockOption&{quantity:string};
export function DonationWorkspace(){const[generation,setGeneration]=React.useState(0);return <Layout title="Donations"><DonationForm key={generation} onNew={()=>setGeneration(v=>v+1)}/></Layout>}
function DonationForm({onNew}:{onNew:()=>void}){
 const{can}=useSession();const[organization,setOrganization]=React.useState<ErpValue>(null);const[unit,setUnit]=React.useState<ErpValue>(null);const[donor,setDonor]=React.useState<ErpValue>(null);const[donee,setDonee]=React.useState<ErpValue>(null);const[term,setTerm]=React.useState("");const[selected,setSelected]=React.useState<Selected[]>([]);const[pending,setPending]=React.useState<DonationRequest|null>(null);const[completed,setCompleted]=React.useState<Donation|null>(null);const[busy,setBusy]=React.useState(false);const[error,setError]=React.useState("");const[refresh,setRefresh]=React.useState(0);
 const organizationId=organization?Number(organization):undefined,unitId=unit?Number(unit):undefined;const canRead=can("donations","READ",organizationId,unitId),canCreate=can("donations","CREATE",organizationId,unitId);const valid=selected.length>0&&selected.every(i=>Number(i.quantity)>0&&Number(i.quantity)<=Number(i.available)&&(i.kind==="LOT"||Number(i.quantity)===1));
 async function finalize(event:React.FormEvent){event.preventDefault();if(!organizationId||!donor||!donee||!term.trim()||!valid||!canCreate||busy)return;const request=pending??{requestId:crypto.randomUUID(),organizationId,unitId,donorId:Number(donor),doneeId:Number(donee),term,items:selected.map(i=>i.kind==="ASSET"?{assetId:i.stockId,quantity:1}:{balanceId:i.stockId,quantity:Number(i.quantity)})};setBusy(true);setPending(request);setError("");try{setCompleted(await api.finalize(request));setPending(null);setRefresh(v=>v+1)}catch(caught){const status=axios.isAxiosError(caught)?caught.response?.status:undefined;if(status&&status>=400&&status<500)setPending(null);setError(errorText(caught))}finally{setBusy(false)}}
 return <div className={styles.workspace}><p className={styles.intro}>Donate available assets or lot-controlled stock under a formal term.</p>{error&&<Message type="error" text={error} onClose={()=>setError("")}/>} {pending&&!busy&&<Message type="warn" text="The result could not be confirmed. Retry the same request to avoid donating stock twice."/>}{completed&&<Message type="success" text={`Donation #${completed.id} finalized successfully.`}/>}<form data-comandos-erp-form="true" onSubmit={finalize}><fieldset className={styles.fields} disabled={busy||!!pending||!!completed}>
  <Field label="Organization *"><ReferenceField service={core} field={ref("organizationId","Organization","organizations")} value={organization} organizationId={null} onChange={v=>{setOrganization(v);setUnit(null);setSelected([])}}/></Field>
  <Field label="Unit"><ReferenceField key={String(organization)} service={core} field={ref("unitId","Unit","units",false)} value={unit} organizationId={organization} onChange={v=>{setUnit(v);setSelected([])}}/></Field>
  <Field label="Donor representative *"><ReferenceField service={core} field={ref("donorId","Donor representative","people")} value={donor} organizationId={null} onChange={setDonor}/></Field>
  <Field label="Donee *"><ReferenceField service={core} field={ref("doneeId","Donee","people")} value={donee} organizationId={null} onChange={setDonee}/></Field>
  <div className={styles.field}><label htmlFor="donation-term">Donation term *</label><input id="donation-term" required maxLength={255} value={term} onChange={e=>setTerm(e.target.value)}/></div>
 </fieldset>{organizationId&&canRead&&canCreate&&!completed&&<StockPicker organizationId={organizationId} unitId={unitId} selected={selected} onAdd={i=>setSelected([...selected,{...i,quantity:"1"}])}/>}<div className={styles.tableContainer}><table><caption>Donation items</caption><thead><tr><th>Item</th><th>Available</th><th>Quantity</th><th className={styles.actionCell}>Actions</th></tr></thead><tbody>{selected.map(i=><tr key={`${i.kind}-${i.stockId}`}><td>{i.code} · {i.modelName}<br/>{i.locationName}</td><td>{i.available} {i.unitOfMeasure}</td><td><input aria-label={`Quantity for ${i.code}`} type="number" min="0.0001" max={i.available} step="0.0001" value={i.quantity} disabled={i.kind==="ASSET"||busy||!!pending||!!completed} onChange={e=>setSelected(selected.map(v=>v.kind===i.kind&&v.stockId===i.stockId?{...v,quantity:e.target.value}:v))}/></td><td className={styles.actionCell}><Button type="button" severity="secondary" disabled={busy||!!pending||!!completed} onClick={()=>setSelected(selected.filter(v=>v.kind!==i.kind||v.stockId!==i.stockId))}>Remove</Button></td></tr>)}{!selected.length&&<tr><td colSpan={4}>Select an organization and add available stock.</td></tr>}</tbody></table></div><div className={styles.actions}>{completed?<Button type="button" className="registration-yellow-button" onClick={onNew}>+ Donation</Button>:<Button type="submit" className="registration-yellow-button" disabled={busy||!valid||!canCreate}>{busy?"Finalizing…":pending?"Retry finalize":"Finalize donation"}</Button>}</div></form>{!canCreate&&<Message type="info" text="Select an organization and an authorized unit when required by your profile."/>}{organizationId&&canRead&&<History organizationId={organizationId} unitId={unitId} refresh={refresh}/>}</div>
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <div className={styles.field}><label>{label}</label>{children}</div>}
function StockPicker({organizationId,unitId,selected,onAdd}:{organizationId:number;unitId?:number;selected:Selected[];onAdd:(i:DonationStockOption)=>void}){const[kind,setKind]=React.useState<"ASSET"|"LOT">("ASSET");const[search,setSearch]=React.useState("");const[page,setPage]=React.useState(0);const[result,setResult]=React.useState<DonationPage<DonationStockOption>|null>(null);const[error,setError]=React.useState("");React.useEffect(()=>{const controller=new AbortController();const timer=setTimeout(()=>api.stock(organizationId,unitId,kind,search,page,controller.signal).then(v=>{if(!controller.signal.aborted){setResult(v);setError("")}}).catch(e=>{if(!controller.signal.aborted)setError(errorText(e))}),250);return()=>{clearTimeout(timer);controller.abort()}},[organizationId,unitId,kind,search,page]);return <section><div className={styles.toolbar}><h2>Available stock</h2><div className={styles.field}><label htmlFor="donation-kind">Stock type</label><select id="donation-kind" value={kind} onChange={e=>{setKind(e.target.value as "ASSET"|"LOT");setPage(0);setResult(null)}}><option value="ASSET">Individual assets</option><option value="LOT">Stock lots</option></select></div><div className={styles.field}><label htmlFor="donation-search">Code, model or SKU</label><input id="donation-search" type="search" value={search} onChange={e=>{setSearch(e.target.value);setPage(0);setResult(null)}}/></div></div>{error&&<Message type="error" text={error}/>} {!result&&!error&&<p role="status">Loading stock…</p>}{result&&<><div className={styles.tableContainer}><table><thead><tr><th>Code / model</th><th>Location</th><th>Available</th><th className={styles.actionCell}>Actions</th></tr></thead><tbody>{result.content.map(i=><tr key={`${i.kind}-${i.stockId}`}><td>{i.code}<br/>{i.modelName} · {i.sku}</td><td>{i.locationName}</td><td>{i.available} {i.unitOfMeasure}</td><td className={styles.actionCell}><Button type="button" disabled={selected.length>=100||selected.some(v=>v.kind===i.kind&&v.stockId===i.stockId)} onClick={()=>onAdd(i)}>Add</Button></td></tr>)}{!result.content.length&&<tr><td colSpan={4}>No available stock matches your search.</td></tr>}</tbody></table></div><Pagination page={page} result={result} onPage={v=>{setPage(v);setResult(null)}}/></>}</section>}
function History({organizationId,unitId,refresh}:{organizationId:number;unitId?:number;refresh:number}){const[page,setPage]=React.useState(0);const[result,setResult]=React.useState<DonationPage<Donation>|null>(null);const[error,setError]=React.useState("");React.useEffect(()=>{const c=new AbortController();api.list(organizationId,unitId,page,c.signal).then(v=>{if(!c.signal.aborted){setResult(v);setError("")}}).catch(e=>{if(!c.signal.aborted)setError(errorText(e))});return()=>c.abort()},[organizationId,unitId,page,refresh]);return <section className="mt-8"><h2>Donation history</h2>{error&&<Message type="error" text={error}/>} {!result&&!error&&<p role="status">Loading history…</p>}{result?.content.map(d=><details key={d.id}><summary>Donation #{d.id} · {d.doneeName} · {d.status}</summary><p>{d.organizationName} · Unit: {d.unitName||"Organization-wide"} · Term: {d.term}</p><p>Donor representative: {d.donorName} · Finalized: {d.finalizedAt.replace("T"," ")} · Operator: {d.finalizedByLogin||"Not recorded"}</p><div className={styles.tableContainer}><table><thead><tr><th>Item</th><th>Location</th><th>Quantity</th></tr></thead><tbody>{d.items.map(i=><tr key={i.id}><td>{i.stockCode} · {i.modelName}<br/>{i.sku}</td><td>{i.locationName}</td><td>{i.quantity} {i.unitOfMeasure}</td></tr>)}</tbody></table></div></details>)}{result&&!result.content.length&&<p>No donations in the selected scope.</p>}{result&&<Pagination page={page} result={result} onPage={setPage}/>}</section>}
function Pagination({page,result,onPage}:{page:number;result:{totalElements:number;size:number};onPage:(p:number)=>void}){return <div className={styles.pagination}><span>{result.totalElements} records · Page {page+1}</span><Button type="button" severity="secondary" disabled={page===0} onClick={()=>onPage(page-1)}>Previous</Button><Button type="button" severity="secondary" disabled={(page+1)*result.size>=result.totalElements} onClick={()=>onPage(page+1)}>Next</Button></div>}
