"use client";import*as React from"react";import axios from"axios";import{Button}from"components/ui/button";import{Layout}from"components/layout";import{Message}from"components/common/message";import{useSession}from"components/auth/session-provider";import{ReferenceField}from"components/erp/shared/record-workspace";import{createErpService}from"api/services/erp.service";import{inventoryCountService as api}from"api/services/inventory-count.service";import type{ErpField,ErpValue}from"api/models/erp";import type{InventoryCount,InventoryCountOpenRequest}from"api/models/erp/inventory-count";import styles from"components/erp/shared/workspace.module.css";
const core=createErpService("core"),inventory=createErpService("inventory"),ref=(n:string,l:string,r:string,required=true):ErpField=>({name:n,label:l,type:"reference",required,reference:r,choices:[]}),errorText=(e:unknown)=>axios.isAxiosError(e)&&typeof e.response?.data?.detail==="string"?e.response.data.detail:"Unable to complete the request. Check the API connection and try again.";
export function InventoryCountPanel(){const[g,setG]=React.useState(0);return <Form key={g} onNew={()=>setG(v=>v+1)}/>}export function InventoryCountWorkspace(){return <Layout title="Physical inventory"><InventoryCountPanel/></Layout>}
function Form({onNew}:{onNew:()=>void}){const{can}=useSession();const[org,setOrg]=React.useState<ErpValue>(null),[unit,setUnit]=React.useState<ErpValue>(null),[location,setLocation]=React.useState<ErpValue>(null),[purpose,setPurpose]=React.useState(""),[current,setCurrent]=React.useState<InventoryCount|null>(null),[history,setHistory]=React.useState<InventoryCount[]>([]),[values,setValues]=React.useState<Record<number,{quantity:string;notes:string}>>({}),[error,setError]=React.useState(""),[busy,setBusy]=React.useState(false),[refresh,setRefresh]=React.useState(0);const[pending,setPending]=React.useState<InventoryCountOpenRequest|null>(null);const submitting=React.useRef(false);const quantitiesValid=!!current&&current.items.every(item=>{const quantity=values[item.id]?.quantity??"";return /^\d{1,15}(\.\d{1,4})?$/.test(quantity)&&(item.kind==="LOT"||Number(quantity)===0||Number(quantity)===1)});const oid=org?Number(org):undefined,uid=unit?Number(unit):undefined,read=!!oid&&can("inventory-counts","READ",oid,uid),create=!!oid&&can("inventory-counts","CREATE",oid,uid);
 React.useEffect(()=>{if(!oid||!read)return;const c=new AbortController();api.list(oid,uid,0,c.signal).then(x=>{if(!c.signal.aborted)setHistory(x.content)}).catch(e=>{if(!c.signal.aborted)setError(errorText(e))});return()=>c.abort()},[oid,uid,read,refresh]);
 function load(c:InventoryCount){setCurrent(c);setValues(Object.fromEntries(c.items.map(i=>[i.id,{quantity:i.countedQuantity??i.systemQuantity,notes:i.notes??""}])))}

 async function open(event:React.FormEvent) {
  event.preventDefault();if(submitting.current||current||!oid||!location||!purpose.trim()||!create)return;
  const request=pending??{requestId:crypto.randomUUID(),organizationId:oid,unitId:uid,locationId:Number(location),purpose};
  submitting.current=true;setBusy(true);setError("");setPending(request);
  try{load(await api.open(request));setPending(null);setRefresh(value=>value+1)}
  catch(error){const status=axios.isAxiosError(error)?error.response?.status:undefined;if(!pending&&status&&status>=400&&status<500)setPending(null);setError(errorText(error))}
  finally{submitting.current=false;setBusy(false)}
 }
 async function submit() {
  if(!current||submitting.current||!quantitiesValid)return;
  submitting.current=true;setBusy(true);setError("");
  try{load(await api.count(current.id,{items:current.items.map(item=>({itemId:item.id,countedQuantity:values[item.id].quantity,notes:values[item.id].notes||null}))}));setRefresh(value=>value+1)}
  catch(error){setError(errorText(error))}finally{submitting.current=false;setBusy(false)}
 }
 async function transition(action:"approve"|"cancel") {
  if(!current||submitting.current)return;
  submitting.current=true;setBusy(true);setError("");
  try{load(await api[action](current.id));setRefresh(value=>value+1)}
  catch(error){setError(errorText(error))}finally{submitting.current=false;setBusy(false)}
 }

 return <div className={styles.workspace}><p className={styles.intro}>Count all individual equipment and lot quantities at one stock location, review differences, and approve auditable adjustments.</p>{error&&<Message type="error" text={error} onClose={()=>setError("")}/>}<form data-comandos-erp-form="true" onSubmit={open}><fieldset className={styles.fields} disabled={busy||!!pending||!!current}><Field label="Organization *"><ReferenceField service={core} field={ref("organizationId","Organization","organizations")} value={org} organizationId={null} onChange={v=>{setOrg(v);setUnit(null);setLocation(null)}}/></Field><Field label="Unit"><ReferenceField service={core} field={ref("unitId","Unit","units",false)} value={unit} organizationId={org} onChange={v=>{setUnit(v);setLocation(null)}}/></Field><Field label="Stock location *"><ReferenceField service={inventory} field={ref("locationId","Stock location","locations")} value={location} organizationId={org} onChange={setLocation}/></Field><Field label="Purpose *"><input value={purpose} onChange={e=>setPurpose(e.target.value)} required/></Field></fieldset>{!current&&<div className={styles.actions}><Button className="registration-yellow-button" disabled={busy||!create||!location}>{pending?"Retry opening count":"Open inventory count"}</Button></div>}</form>
 {pending&&!busy&&<Message type="warn" text="The result could not be confirmed. Retry to recover the same inventory count."/>}{current&&<section><h2>Inventory count #{current.id} · {current.statusName}</h2><p>{current.locationName} · {current.purpose}</p><div className={styles.tableContainer}><table><thead><tr><th>Item</th><th>System</th><th>Counted</th><th>Difference</th><th>Result</th><th>Notes</th></tr></thead><tbody>{current.items.map(i=><tr key={i.id}><td>{i.stockCode} · {i.modelName}</td><td>{i.systemQuantity} {i.unitOfMeasure}</td><td><input aria-label={`Counted quantity for ${i.stockCode}`} type="number" min="0" max={i.kind==="ASSET"?1:undefined} step={i.kind==="ASSET"?1:".0001"} disabled={busy||!['OPEN','COUNTED'].includes(current.statusCode)} value={values[i.id]?.quantity??""} onChange={e=>setValues({...values,[i.id]:{quantity:e.target.value,notes:values[i.id]?.notes??""}})}/></td><td>{i.differenceQuantity??"—"}</td><td>{i.resultName??"Pending"}</td><td><input aria-label={`Count notes for ${i.stockCode}`} disabled={busy||!['OPEN','COUNTED'].includes(current.statusCode)} value={values[i.id]?.notes??""} onChange={e=>setValues({...values,[i.id]:{quantity:values[i.id]?.quantity??"",notes:e.target.value}})}/></td></tr>)}</tbody></table></div><div className={styles.actions}>{['OPEN','COUNTED'].includes(current.statusCode)&&<Button type="button" onClick={submit} disabled={busy||!quantitiesValid||!can("inventory-counts","COUNT",oid,uid)}>Save count</Button>}{current.statusCode==="COUNTED"&&<Button type="button" className="registration-yellow-button" onClick={()=>transition("approve")} disabled={busy||!can("inventory-counts","APPROVE",oid,uid)}>Approve adjustments</Button>}{['OPEN','COUNTED'].includes(current.statusCode)&&<Button type="button" severity="secondary" onClick={()=>transition("cancel")} disabled={busy||!can("inventory-counts","CANCEL",oid,uid)}>Cancel</Button>}<Button type="button" severity="secondary" disabled={busy||!!pending} onClick={onNew}>+ Inventory count</Button></div></section>}
 {oid&&read&&<section><h2>Inventory history</h2>{history.map(c=><details key={c.id}><summary>#{c.id} · {c.locationName} · {c.statusName}</summary><p>{c.purpose} · opened {c.openedAt.replace("T"," ")}</p><Button type="button" severity="secondary" disabled={busy||!!pending} onClick={()=>load(c)}>View</Button></details>)}</section>}</div>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <div className={styles.field}><label>{label}</label>{children}</div>}
