package com.weaponsregistration.report.service;
import com.weaponsregistration.audit.model.AuditRecord;import com.weaponsregistration.custody.model.Custody;import com.weaponsregistration.inventory.model.*;import com.weaponsregistration.maintenance.model.WorkOrder;
import com.weaponsregistration.reconciliation.model.InventoryCount;import com.weaponsregistration.report.dto.ArmamentReportContract.*;import com.weaponsregistration.security.service.AccessPolicy;import com.weaponsregistration.workflow.model.ApprovalWorkflow;
import com.weaponsregistration.lifecycle.model.ExceptionOccurrence;import jakarta.persistence.EntityManager;import java.math.BigDecimal;import java.time.*;import java.util.*;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;
@Service@Transactional(readOnly=true)public class ArmamentReportService{private final EntityManager em;private final AccessPolicy access;public ArmamentReportService(EntityManager em,AccessPolicy access){this.em=em;this.access=access;}
 public Dashboard dashboard(long org,Long unit){access.requireScope("inventory/assets","READ",org,unit);String aScope=unit==null?"a.location.organization.id=:o":"a.location.organization.id=:o and a.location.unit.id=:u";String bScope=unit==null?"b.location.organization.id=:o":"b.location.organization.id=:o and b.location.unit.id=:u";long total=count("select count(a) from AssetItem a where "+aScope,org,unit);long available=count("select count(a) from AssetItem a where "+aScope+" and a.status='AVAILABLE'",org,unit);long custody=count("select count(a) from AssetItem a where "+aScope+" and a.status='CUSTODIED'",org,unit);long maintenance=count("select count(a) from AssetItem a where "+aScope+" and a.status='IN_MAINTENANCE'",org,unit);long blocked=count("select count(a) from AssetItem a where "+aScope+" and a.status in ('BLOCKED','MISSING','RESTRICTED')",org,unit);BigDecimal stock=sum("select coalesce(sum(b.available),0) from StockBalance b where "+bScope,org,unit);String cScope=unit==null?"c.organization.id=:o":"c.organization.id=:o and c.unit.id=:u";long overdue=count("select count(c) from Custody c where "+cScope+" and c.status='ACTIVE' and c.dueAt is not null and c.dueAt<:now",org,unit,"now",LocalDateTime.now());String xScope=unit==null?"x.organization.id=:o":"x.organization.id=:o and x.unit.id=:u";long occurrences=count("select count(x) from ExceptionOccurrence x where "+xScope+" and x.status='OPEN'",org,unit);long expired=count("select count(x) from ExpirationRecord x where "+xScope+" and x.expirationDate<:today and x.status<>'RESOLVED'",org,unit,"today",LocalDate.now());long workflows=count("select count(x) from ApprovalWorkflow x where "+xScope+" and x.status not in ('CONCLUDED','CANCELLED')",org,unit);long divergences=count("select count(x) from InventoryCount x where "+xScope+" and x.status.code='APPROVED' and exists(select i.id from InventoryCountItem i where i.inventoryCount=x and i.result.code<>'MATCH')",org,unit);return new Dashboard(total,available,custody,maintenance,blocked,stock,overdue,occurrences,expired,workflows,divergences);}
 public List<Alert>alerts(long org,Long unit){var d=dashboard(org,unit);List<Alert>a=new ArrayList<>();if(d.overdueCustodies()>0)a.add(new Alert("HIGH","OVERDUE_CUSTODY",d.overdueCustodies()+" overdue custody records","custody",null));if(d.openOccurrences()>0)a.add(new Alert("HIGH","OPEN_OCCURRENCE",d.openOccurrences()+" exceptional occurrences require attention","occurrences",null));if(d.expiredCompliance()>0)a.add(new Alert("HIGH","EXPIRED_COMPLIANCE",d.expiredCompliance()+" compliance records are expired","compliance",null));if(d.inventoryDivergences()>0)a.add(new Alert("MEDIUM","INVENTORY_DIVERGENCE",d.inventoryDivergences()+" inventory counts contain divergences","inventory",null));if(d.pendingWorkflows()>0)a.add(new Alert("MEDIUM","PENDING_APPROVAL",d.pendingWorkflows()+" workflows await action","workflow",null));return a;}
 public List<Position>assets(long org,Long unit,String q){access.requireScope("inventory/assets","READ",org,unit);String scope=unit==null?"a.location.organization.id=:o":"a.location.organization.id=:o and a.location.unit.id=:u";String search=q==null||q.isBlank()?"":" and (lower(a.assetCode) like :q or lower(coalesce(a.serialNumber,'')) like :q or lower(a.model.name) like :q)";var x=em.createQuery("select a from AssetItem a where "+scope+search+" order by a.id desc",AssetItem.class).setParameter("o",org);if(unit!=null)x.setParameter("u",unit);if(!search.isEmpty())x.setParameter("q","%"+q.trim().toLowerCase(Locale.ROOT)+"%");return x.setMaxResults(200).getResultList().stream().map(a->new Position(a.id,a.assetCode,a.serialNumber,a.model.name,a.status,a.condition,a.location.name,a.location.unit==null?null:a.location.unit.name)).toList();}
 public List<LotPosition>lots(long org,Long unit){access.requireScope("inventory/assets","READ",org,unit);String scope=unit==null?"b.location.organization.id=:o":"b.location.organization.id=:o and b.location.unit.id=:u";var x=em.createQuery("select b from StockBalance b where "+scope+" order by b.id desc",StockBalance.class).setParameter("o",org);if(unit!=null)x.setParameter("u",unit);return x.setMaxResults(200).getResultList().stream().map(b->new LotPosition(b.lot.id,b.lot.lotNumber,b.lot.model.name,b.location.name,b.available,b.reserved,b.blocked,b.lot.validUntil==null?null:b.lot.validUntil.toString())).toList();}
 public List<History>history(String resource,Long recordId){return history(resource,recordId,null,null);}
 private List<History>history(String resource,Long recordId,Long org,Long unit){access.requireAny("audit","READ");String w=" where 1=1"+(resource==null||resource.isBlank()?"":" and a.resource=:r")+(recordId==null?"":" and a.recordId=:id");if(org!=null)w+=" and exists(select r.id from AuditReference r where r.eventId=a.id and r.kind='organization' and r.targetId=:org)";if(unit!=null)w+=" and exists(select r.id from AuditReference r where r.eventId=a.id and r.kind='unit' and r.targetId=:unit)";var q=em.createQuery("select a from AuditRecord a"+w+" order by a.id desc",AuditRecord.class);if(resource!=null&&!resource.isBlank())q.setParameter("r",resource);if(recordId!=null)q.setParameter("id",recordId);if(org!=null)q.setParameter("org",org);if(unit!=null)q.setParameter("unit",unit);return q.setMaxResults(500).getResultList().stream().map(a->new History("AUDIT",a.id,a.occurredAt.toString(),a.action,a.resource+"#"+a.recordId,a.actorLogin)).toList();}
 public Bundle bundle(long org,Long unit){return new Bundle(dashboard(org,unit),alerts(org,unit),assets(org,unit,null),lots(org,unit),history(null,null,org,unit).stream().limit(50).toList());}
 private long count(String jpql,long org,Long unit,Object...p){var q=em.createQuery(jpql,Long.class).setParameter("o",org);if(unit!=null)q.setParameter("u",unit);for(int i=0;i<p.length;i+=2)q.setParameter((String)p[i],p[i+1]);return q.getSingleResult();}
 private BigDecimal sum(String jpql,long org,Long unit){var q=em.createQuery(jpql,BigDecimal.class).setParameter("o",org);if(unit!=null)q.setParameter("u",unit);return q.getSingleResult();}
}