product.id=comandos
modules=enterprise.tenancy,enterprise.design-system,enterprise.application-builder,enterprise.organization,enterprise.personnel,enterprise.catalog,enterprise.inventory,enterprise.procurement,enterprise.sales,enterprise.finance,enterprise.contracts,comandos.armament,comandos.transport,comandos.escort,comandos.intelligence,comandos.operations
module.enterprise.tenancy.version=1
module.enterprise.design-system.version=1
module.enterprise.application-builder.version=1
module.enterprise.organization.version=1
module.enterprise.personnel.version=1
module.enterprise.catalog.version=1
module.enterprise.inventory.version=1
module.enterprise.procurement.version=1
module.enterprise.sales.version=1
module.enterprise.finance.version=1
module.enterprise.contracts.version=1
module.comandos.armament.version=1
module.comandos.transport.version=1
module.comandos.escort.version=1
module.comandos.intelligence.version=1
module.comandos.operations.version=1
