package com.comandos.workflow.service;
import com.comandos.audit.service.AuditService;import com.comandos.core.model.*;import com.comandos.security.service.AccessPolicy;
import com.comandos.workflow.dto.WorkflowContract.*;import com.comandos.workflow.model.*;import jakarta.persistence.*;import java.time.*;import java.util.*;
import org.springframework.http.*;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import org.springframework.web.server.ResponseStatusException;
@Service@Transactional(readOnly=true)public class WorkflowService{
 private final EntityManager em;private final AccessPolicy access;private final AuditService audit;
 public WorkflowService(EntityManager em,AccessPolicy access,AuditService audit){this.em=em;this.access=access;this.audit=audit;}
 @Transactional public View request(Request r){if(r==null||r.organizationId()==null||blank(r.operationType())||blank(r.resource())||blank(r.justification()))bad("Organization, operation, resource and justification are required.");access.requireScope("inventory/assets","CREATE",r.organizationId(),r.unitId());var w=new ApprovalWorkflow();w.organization=find(Organization.class,r.organizationId());w.unit=r.unitId()==null?null:find(OrganizationalUnit.class,r.unitId());if(w.unit!=null&&!w.unit.organization.id.equals(w.organization.id))bad("Unit does not belong to organization.");w.operationType=r.operationType().trim().toUpperCase(Locale.ROOT);w.resource=r.resource().trim();w.recordId=r.recordId();w.justification=r.justification().trim();w.requestedAt=LocalDateTime.now();var a=audit.actor();w.requestedById=a.id();w.requestedByLogin=a.login();em.persist(w);em.flush();event(w,"NONE","REQUESTED",w.justification);var v=view(w);audit.record("approval-workflows",w.id,"CREATE",null,v);return v;}
 @Transactional public View analyze(long id,Transition r){return move(id,"REQUESTED","ANALYZED",r,false);}
 @Transactional public View authorize(long id,Transition r){return move(id,"ANALYZED","AUTHORIZED",r,true);}
 @Transactional public View execute(long id,Transition r){return move(id,"AUTHORIZED","EXECUTED",r,false);}
 @Transactional public View conclude(long id,Transition r){return move(id,"EXECUTED","CONCLUDED",r,false);}
 @Transactional public View cancel(long id,Transition r){var w=locked(id);if(Set.of("CONCLUDED","CANCELLED").contains(w.status))bad("Completed workflow cannot be cancelled.");return moveAny(w,"CANCELLED",r,false);}
 public View get(long id){var w=find(ApprovalWorkflow.class,id);access.requireScope("inventory/assets","READ",w.organization.id,w.unit==null?null:w.unit.id);return view(w);}
 public Page<View> list(long org,Long unit,String status,int page){access.requireScope("inventory/assets","READ",org,unit);String where=" where w.organization.id=:o"+(unit==null?"":" and w.unit.id=:u")+(blank(status)?"":" and w.status=:s");var q=em.createQuery("select w from ApprovalWorkflow w"+where+" order by w.id desc",ApprovalWorkflow.class);var c=em.createQuery("select count(w) from ApprovalWorkflow w"+where,Long.class);q.setParameter("o",org);c.setParameter("o",org);if(unit!=null){q.setParameter("u",unit);c.setParameter("u",unit);}if(!blank(status)){q.setParameter("s",status.trim().toUpperCase(Locale.ROOT));c.setParameter("s",status.trim().toUpperCase(Locale.ROOT));}return new Page<>(q.setFirstResult(page*20).setMaxResults(20).getResultList().stream().map(this::view).toList(),c.getSingleResult(),page,20);}
 private View move(long id,String expected,String target,Transition r,boolean authority){var w=locked(id);if(!expected.equals(w.status))bad("Invalid workflow transition from "+w.status+" to "+target+".");return moveAny(w,target,r,authority);}
 private View moveAny(ApprovalWorkflow w,String target,Transition r,boolean authority){access.requireScope("inventory/assets","UPDATE",w.organization.id,w.unit==null?null:w.unit.id);String reason=r==null||blank(r.justification())?"Workflow transition":r.justification().trim();var before=view(w);String from=w.status;w.status=target;var now=LocalDateTime.now();var a=audit.actor();if(authority){w.authorityId=a.id();w.authorityLogin=a.login();w.authorizedAt=now;}if("EXECUTED".equals(target))w.executedAt=now;if("CONCLUDED".equals(target))w.concludedAt=now;if("CANCELLED".equals(target))w.cancelledAt=now;event(w,from,target,reason);em.flush();var v=view(w);audit.record("approval-workflows",w.id,target,before,v);return v;}
 private void event(ApprovalWorkflow w,String from,String to,String reason){var e=new ApprovalWorkflowEvent();e.workflow=w;e.fromStatus=from;e.toStatus=to;e.justification=reason;e.occurredAt=LocalDateTime.now();var a=audit.actor();e.actorId=a.id();e.actorLogin=a.login();em.persist(e);}
 private View view(ApprovalWorkflow w){var es=em.createQuery("select e from ApprovalWorkflowEvent e where e.workflow.id=:id order by e.id",ApprovalWorkflowEvent.class).setParameter("id",w.id).getResultList().stream().map(e->new EventView(e.id,e.fromStatus,e.toStatus,e.justification,e.occurredAt.toString(),e.actorLogin)).toList();return new View(w.id,w.organization.id,w.unit==null?null:w.unit.id,w.operationType,w.resource,w.recordId,w.status,w.justification,w.requestedAt.toString(),w.requestedByLogin,w.authorityLogin,s(w.authorizedAt),s(w.executedAt),s(w.concludedAt),s(w.cancelledAt),es);}
 private ApprovalWorkflow locked(long id){var w=em.find(ApprovalWorkflow.class,id,LockModeType.PESSIMISTIC_WRITE);if(w==null)notFound();return w;}private<T>T find(Class<T>c,long id){var x=em.find(c,id);if(x==null)notFound();return x;}private static String s(LocalDateTime x){return x==null?null:x.toString();}private static boolean blank(String s){return s==null||s.isBlank();}private static void bad(String s){throw new ResponseStatusException(HttpStatus.BAD_REQUEST,s);}private static void notFound(){throw new ResponseStatusException(HttpStatus.NOT_FOUND,"Record not found.");}
}