"use client";
import * as React from "react";
import { confirmMovement } from "components/erp/shared/confirm-movement";
import axios from "axios";
import { Button } from "components/common/button";
import { ComandosSelectField } from "components/common/select-field";
import { Layout } from "components/layout";
import { Message } from "components/common/message";
import { useSession } from "components/auth/session-provider";
import { ReferenceField } from "components/erp/shared/record-workspace";
import { createErpService } from "api/services/erp.service";
import { disposalService as api } from "api/services/disposal.service";
import type { ErpField,ErpValue } from "api/models/erp";
import type { DisposalPage,DisposalProcess,DisposalRequest,DisposalStockOption } from "api/models/erp/disposal";
import styles from "components/erp/shared/workspace.module.css";
const core=createErpService("core");
const ref=(name:string,label:string,resource:string,required=true):ErpField=>({name,label,type:"reference",required,reference:resource,choices:[]});
const errorText=(error:unknown)=>axios.isAxiosError(error)&&typeof error.response?.data?.detail==="string"?error.response.data.detail:"Unable to complete the request. Check the API connection and try again.";
type Selected=DisposalStockOption&{quantity:string};
export function DisposalPanel(){const[generation,setGeneration]=React.useState(0);return <DisposalForm key={generation} onNew={()=>setGeneration(value=>value+1)}/>}export function DisposalWorkspace(){return <Layout title="Asset disposal"><DisposalPanel/></Layout>}
function DisposalForm({onNew}:{onNew:()=>void}){
 const{can}=useSession();const submitting=React.useRef(false);const[organization,setOrganization]=React.useState<ErpValue>(null);const[unit,setUnit]=React.useState<ErpValue>(null);const[processNumber,setProcessNumber]=React.useState("");const[reason,setReason]=React.useState("");const[destroy,setDestroy]=React.useState(false);const[method,setMethod]=React.useState("");const[destroyedAt,setDestroyedAt]=React.useState("");const[certificate,setCertificate]=React.useState("");const[selected,setSelected]=React.useState<Selected[]>([]);const[pending,setPending]=React.useState<DisposalRequest|null>(null);const[completed,setCompleted]=React.useState<DisposalProcess|null>(null);const[busy,setBusy]=React.useState(false);const[error,setError]=React.useState("");const[refresh,setRefresh]=React.useState(0);
 const organizationId=organization?Number(organization):undefined,unitId=unit?Number(unit):undefined;const canRead=can("disposals","READ",organizationId,unitId),canCreate=can("disposals","CREATE",organizationId,unitId)&&can("disposals","APPROVE",organizationId,unitId);const validItems=selected.length>0&&selected.every(item=>Number(item.quantity)>0&&Number(item.quantity)<=Number(item.available)&&(item.kind==="LOT"||Number(item.quantity)===1));const validDestruction=!destroy||!!method.trim()&&!!destroyedAt&&!!certificate.trim();
 async function finalize(event:React.FormEvent){event.preventDefault();if(!organizationId||!processNumber.trim()||!reason.trim()||!validItems||!validDestruction||!canCreate||busy||submitting.current||completed)return;if(!pending&&!confirmMovement(event.currentTarget as HTMLFormElement,"Result: permanently remove the selected stock.",`Destruction: ${destroy ? method + " ? " + destroyedAt + " ? " + certificate : "Not recorded"}\n`+selected.map(i=>`${i.code} ? ${i.modelName} ? ${i.locationName} ? ${i.quantity} ${i.unitOfMeasure}`).join("\n")))return;const request=pending??{requestId:crypto.randomUUID(),confirmed:true,organizationId,unitId,processNumber,reason,destructionMethod:destroy?method:undefined,destroyedAt:destroy?destroyedAt:undefined,destructionCertificate:destroy?certificate:undefined,items:selected.map(item=>item.kind==="ASSET"?{assetId:item.stockId,quantity:1}:{balanceId:item.stockId,quantity:Number(item.quantity)})};submitting.current=true;setBusy(true);setPending(request);setError("");try{setCompleted(await api.finalize(request));setPending(null);setRefresh(value=>value+1)}catch(caught){const status=axios.isAxiosError(caught)?caught.response?.status:undefined;if(!pending&&status&&status>=400&&status<500)setPending(null);setError(errorText(caught))}finally{submitting.current=false;setBusy(false)}}
 return <div className={styles.workspace}><p className={styles.intro}>Disposal permanently removes assets or lot quantities from use. It is not temporary inactivation (BLOCKED). Physical destruction is recorded only with its method, date and certificate. Finalization requires CREATE and APPROVE permissions.</p>{error&&<Message type="error" text={error} onClose={()=>setError("")}/>} {pending&&!busy&&<Message type="warn" text="The result could not be confirmed. Retry the same request to avoid disposing stock twice."/>}{completed&&<Message type="success" text={`Disposal process #${completed.id} finalized successfully.`}/>}<form data-comandos-erp-form="true" onSubmit={finalize}><fieldset className={styles.fields} disabled={busy||!!pending||!!completed}>
  <Field label="Organization *"><ReferenceField service={core} field={ref("organizationId","Organization","organizations")} value={organization} organizationId={null} onChange={value=>{setOrganization(value);setUnit(null);setSelected([])}}/></Field>
  <Field label="Unit"><ReferenceField key={String(organization)} service={core} field={ref("unitId","Unit","units",false)} value={unit} organizationId={organization} onChange={value=>{setUnit(value);setSelected([])}}/></Field>
  <div className={styles.field}><label htmlFor="disposal-process">Process number *</label><input id="disposal-process" required maxLength={255} value={processNumber} onChange={event=>setProcessNumber(event.target.value)}/></div>
  <div className={styles.field}><label htmlFor="disposal-reason">Reason *</label><input id="disposal-reason" required maxLength={255} value={reason} onChange={event=>setReason(event.target.value)}/></div>
  <div className={styles.field}><label><input type="checkbox" checked={destroy} onChange={event=>setDestroy(event.target.checked)}/> Record physical destruction</label><small>Enable when disposal includes certified destruction.</small></div>
  {destroy&&<><div className={styles.field}><label htmlFor="destruction-method">Destruction method *</label><input id="destruction-method" required maxLength={255} value={method} onChange={event=>setMethod(event.target.value)}/></div><div className={styles.field}><label htmlFor="destroyed-at">Destruction date and time *</label><input id="destroyed-at" type="datetime-local" required value={destroyedAt} onChange={event=>setDestroyedAt(event.target.value)}/></div><div className={styles.field}><label htmlFor="destruction-certificate">Destruction certificate *</label><input id="destruction-certificate" required maxLength={255} value={certificate} onChange={event=>setCertificate(event.target.value)}/></div></>}
 </fieldset>{organizationId&&canRead&&canCreate&&!completed&&!busy&&!pending&&<StockPicker key={`${organizationId}-${unitId}`} organizationId={organizationId} unitId={unitId} selected={selected} onAdd={item=>setSelected([...selected,{...item,quantity:"1"}])}/>}<div className={styles.tableContainer}><table><caption>Disposal items</caption><thead><tr><th>Item</th><th>Location</th><th>Available</th><th>Quantity</th><th className={styles.actionCell}>Actions</th></tr></thead><tbody>{selected.map(item=><tr key={`${item.kind}-${item.stockId}`}><td>{item.code}<br/>{item.modelName} · {item.sku}</td><td>{item.locationName}</td><td>{item.available} {item.unitOfMeasure}</td><td><input aria-label={`Quantity for ${item.code}`} type="number" min="0.0001" max={item.available} step="0.0001" value={item.quantity} disabled={item.kind==="ASSET"||busy||!!pending||!!completed} onChange={event=>setSelected(selected.map(value=>value.kind===item.kind&&value.stockId===item.stockId?{...value,quantity:event.target.value}:value))}/></td><td className={styles.actionCell}><Button type="button" severity="secondary" disabled={busy||!!pending||!!completed} onClick={()=>setSelected(selected.filter(value=>value.kind!==item.kind||value.stockId!==item.stockId))}>Remove</Button></td></tr>)}{!selected.length&&<tr><td colSpan={5}>Select an organization and add available stock.</td></tr>}</tbody></table></div><div className={styles.actions}>{completed?<Button type="button" className="registration-yellow-button" onClick={onNew}>+ Disposal</Button>:<Button type="submit" className="registration-yellow-button" disabled={busy||!validItems||!validDestruction||!canCreate||!processNumber.trim()||!reason.trim()}>{busy?"Finalizing…":pending?"Retry finalize":"Finalize disposal"}</Button>}</div></form>{!canCreate&&<Message type="info" text="Select an organization and an authorized unit when required by your profile."/>}{organizationId&&canRead&&<History key={`${organizationId}-${unitId}`} organizationId={organizationId} unitId={unitId} refresh={refresh}/>}</div>
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <div className={styles.field}><label>{label}</label>{children}</div>}
function StockPicker({organizationId,unitId,selected,onAdd}:{organizationId:number;unitId?:number;selected:Selected[];onAdd:(item:DisposalStockOption)=>void}){const[kind,setKind]=React.useState<"ASSET"|"LOT">("ASSET");const[search,setSearch]=React.useState("");const[page,setPage]=React.useState(0);const[result,setResult]=React.useState<DisposalPage<DisposalStockOption>|null>(null);const[error,setError]=React.useState("");React.useEffect(()=>{const controller=new AbortController();const timer=setTimeout(()=>api.stock(organizationId,unitId,kind,search,page,controller.signal).then(value=>{if(!controller.signal.aborted){setResult(value);setError("")}}).catch(caught=>{if(!controller.signal.aborted)setError(errorText(caught))}),250);return()=>{clearTimeout(timer);controller.abort()}},[organizationId,unitId,kind,search,page]);return <section><div className={styles.toolbar}><h2>Available stock</h2><div className={styles.field}><ComandosSelectField id="disposal-kind" label="Stock type" value={kind} options={[{value:"ASSET",label:"Individual assets"},{value:"LOT",label:"Stock lots"}]} onChange={value=>{setKind(value as "ASSET"|"LOT");setPage(0);setResult(null)}} /></div><div className={styles.field}><label htmlFor="disposal-search">Code, model or SKU</label><input id="disposal-search" type="search" value={search} onChange={event=>{setSearch(event.target.value);setPage(0);setResult(null)}}/></div></div>{error&&<Message type="error" text={error}/>} {!result&&!error&&<p role="status">Loading stock…</p>}{result&&<><div className={styles.tableContainer}><table><thead><tr><th>Code / model</th><th>Location</th><th>Available</th><th className={styles.actionCell}>Actions</th></tr></thead><tbody>{result.content.map(item=><tr key={`${item.kind}-${item.stockId}`}><td>{item.code}<br/>{item.modelName} · {item.sku}</td><td>{item.locationName}</td><td>{item.available} {item.unitOfMeasure}</td><td className={styles.actionCell}><Button type="button" disabled={selected.length>=100||selected.some(value=>value.kind===item.kind&&value.stockId===item.stockId)} onClick={()=>onAdd(item)}>Add</Button></td></tr>)}{!result.content.length&&<tr><td colSpan={4}>No available stock matches your search.</td></tr>}</tbody></table></div><Pagination page={page} result={result} onPage={value=>{setPage(value);setResult(null)}}/></>}</section>}
function History({organizationId,unitId,refresh}:{organizationId:number;unitId?:number;refresh:number}){const[page,setPage]=React.useState(0);const[result,setResult]=React.useState<DisposalPage<DisposalProcess>|null>(null);const[error,setError]=React.useState("");React.useEffect(()=>{const controller=new AbortController();api.list(organizationId,unitId,page,controller.signal).then(value=>{if(!controller.signal.aborted){setResult(value);setError("")}}).catch(caught=>{if(!controller.signal.aborted)setError(errorText(caught))});return()=>controller.abort()},[organizationId,unitId,page,refresh]);return <section className="mt-8"><h2>Disposal history</h2>{error&&<Message type="error" text={error}/>} {!result&&!error&&<p role="status">Loading history…</p>}{result?.content.map(process=><details key={process.id}><summary>{process.processNumber} · {process.status}</summary><p>{process.organizationName} · Unit: {process.unitName||"Organization-wide"} · Reason: {process.reason}</p><p>Finalized: {process.finalizedAt.replace("T"," ")} · Operator: {process.finalizedByLogin||"Not recorded"}</p>{!process.destructionMethod&&<p>Logical disposal only. Physical destruction was not recorded.</p>}{process.destructionMethod&&<p>Destruction: {process.destructionMethod} · {process.destroyedAt?.replace("T"," ")} · Certificate: {process.destructionCertificate}</p>}<div className={styles.tableContainer}><table><thead><tr><th>Item</th><th>Location</th><th>Quantity</th></tr></thead><tbody>{process.items.map(item=><tr key={item.id}><td>{item.stockCode} · {item.modelName}<br/>{item.sku}</td><td>{item.locationName}</td><td>{item.quantity} {item.unitOfMeasure}</td></tr>)}</tbody></table></div></details>)}{result&&!result.content.length&&<p>No disposals in the selected scope.</p>}{result&&<Pagination page={page} result={result} onPage={setPage}/>}</section>}
function Pagination({page,result,onPage}:{page:number;result:{totalElements:number;size:number};onPage:(page:number)=>void}){return <div className={styles.pagination}><span>{result.totalElements} records · Page {page+1}</span><Button type="button" severity="secondary" disabled={page===0} onClick={()=>onPage(page-1)}>Previous</Button><Button type="button" severity="secondary" disabled={(page+1)*result.size>=result.totalElements} onClick={()=>onPage(page+1)}>Next</Button></div>}
