-- Oracle compatibility schema for COMANDOS.
-- This file is intentionally idempotent through spring.sql.init.continue-on-error=true:
-- statements for objects that already exist are ignored, while missing objects are created
-- before Hibernate validates the mapped schema.

create table erp_organization_nature (
    id number(19,0) generated by default as identity primary key,
    version number(19,0) not null,
    created_at timestamp(6) not null,
    updated_at timestamp(6) not null,
    code varchar2(80 char) not null,
    name varchar2(255 char) not null,
    description varchar2(255 char),
    active boolean not null
);

create unique index uk_organization_nature_code on erp_organization_nature (code);

create table erp_economic_activity (
    id number(19,0) generated by default as identity primary key,
    version number(19,0) not null,
    created_at timestamp(6) not null,
    updated_at timestamp(6) not null,
    code varchar2(40 char) not null,
    description varchar2(255 char) not null,
    active boolean not null
);

create unique index uk_economic_activity_code on erp_economic_activity (code);

alter table erp_organization add nature_id number(19,0);
alter table erp_organization add economic_activity_id number(19,0);

alter table erp_person_address add country varchar2(120 char);
alter table erp_person_address add foreign_address boolean;
alter table erp_person_address modify postal_code null;

create table erp_person_phone (
    id number(19,0) generated by default as identity primary key,
    version number(19,0) not null,
    created_at timestamp(6) not null,
    updated_at timestamp(6) not null,
    person_id number(19,0) not null,
    phone_type varchar2(40 char) not null,
    country_code varchar2(8 char),
    phone_number varchar2(40 char) not null,
    whatsapp boolean not null,
    primary_phone boolean not null
);

create table erp_person_email (
    id number(19,0) generated by default as identity primary key,
    version number(19,0) not null,
    created_at timestamp(6) not null,
    updated_at timestamp(6) not null,
    person_id number(19,0) not null,
    email_type varchar2(40 char) not null,
    email_address varchar2(255 char) not null,
    primary_email boolean not null
);

create table erp_person_contact_type (
    id number(19,0) generated by default as identity primary key,
    version number(19,0) not null,
    created_at timestamp(6) not null,
    updated_at timestamp(6) not null,
    code varchar2(80 char) not null,
    name varchar2(255 char) not null,
    description varchar2(255 char),
    address_enabled boolean not null,
    phone_enabled boolean not null,
    email_enabled boolean not null,
    active boolean not null
);

create unique index uk_person_contact_type_code on erp_person_contact_type (code);

alter table erp_person_address add contact_type_id number(19,0);
alter table erp_person_phone add contact_type_id number(19,0);
alter table erp_person_email add contact_type_id number(19,0);

create table erp_armament_parameter (
    id number(19,0) generated by default as identity primary key,
    version number(19,0) not null,
    created_at timestamp(6) not null,
    updated_at timestamp(6) not null,
    parameter_type varchar2(60 char) not null,
    code varchar2(80 char) not null,
    name varchar2(255 char) not null,
    description varchar2(255 char),
    active boolean not null
);

create unique index uk_armament_parameter_code on erp_armament_parameter (parameter_type, code);
create unique index uk_armament_parameter_name on erp_armament_parameter (parameter_type, name);

alter table erp_firearm_specification add caliber_id number(19,0);

alter table erp_ammunition_specification add caliber_id number(19,0);
alter table erp_ammunition_specification add ammunition_type_id number(19,0);
alter table erp_ammunition_specification add projectile_type_id number(19,0);
alter table erp_ammunition_specification add case_type_id number(19,0);
alter table erp_ammunition_specification add primer_type_id number(19,0);

alter table erp_grenade_specification add grenade_type_id number(19,0);
alter table erp_grenade_specification add agent_id number(19,0);
alter table erp_grenade_specification add composition_id number(19,0);

alter table erp_spray_specification add agent_id number(19,0);
alter table erp_spray_specification add composition_id number(19,0);

alter table erp_ballistic_protection_specification add protection_type_id number(19,0);
alter table erp_ballistic_protection_specification add protection_level_id number(19,0);
alter table erp_ballistic_protection_specification add material_id number(19,0);
alter table erp_ballistic_protection_specification add size_id number(19,0);

alter table erp_electrical_device_specification add cartridge_type_id number(19,0);
alter table erp_optical_specification add optical_type_id number(19,0);

alter table erp_helmet_specification add protection_level_id number(19,0);
alter table erp_helmet_specification add material_id number(19,0);
alter table erp_helmet_specification add size_id number(19,0);

alter table erp_shield_specification add shield_type_id number(19,0);
alter table erp_shield_specification add protection_level_id number(19,0);
alter table erp_shield_specification add material_id number(19,0);

alter table erp_restraint_specification add material_id number(19,0);
alter table erp_restraint_specification add locking_mechanism_id number(19,0);

alter table erp_accessory_component_specification add component_type_id number(19,0);
alter table erp_accessory_component_specification add compatibility_id number(19,0);
alter table erp_accessory_component_specification add interface_id number(19,0);

alter table erp_tactical_equipment_specification add material_id number(19,0);
alter table erp_tactical_equipment_specification add size_id number(19,0);
