-- Oracle compatibility schema for COMANDOS.
-- This file is intentionally idempotent through spring.sql.init.continue-on-error=true:
-- statements for objects that already exist are ignored, while missing objects are created
-- before Hibernate validates the mapped schema.

create table erp_organization_nature (
    id number(19,0) generated by default as identity primary key,
    version number(19,0) not null,
    created_at timestamp(6) not null,
    updated_at timestamp(6) not null,
    code varchar2(80 char) not null,
    name varchar2(255 char) not null,
    description varchar2(255 char),
    active boolean not null
);

create unique index uk_organization_nature_code on erp_organization_nature (code);

create table erp_economic_activity (
    id number(19,0) generated by default as identity primary key,
    version number(19,0) not null,
    created_at timestamp(6) not null,
    updated_at timestamp(6) not null,
    code varchar2(40 char) not null,
    description varchar2(255 char) not null,
    active boolean not null
);

create unique index uk_economic_activity_code on erp_economic_activity (code);

alter table erp_organization add nature_id number(19,0);
alter table erp_organization add economic_activity_id number(19,0);

create table erp_organizational_unit_type (
    id number(19,0) generated by default as identity primary key,
    version number(19,0) not null,
    created_at timestamp(6) not null,
    updated_at timestamp(6) not null,
    code varchar2(80 char) not null,
    name varchar2(255 char) not null,
    description varchar2(255 char),
    active boolean not null
);

create unique index uk_organizational_unit_type_code on erp_organizational_unit_type (code);

alter table erp_organizational_unit add unit_type_id number(19,0);

alter table erp_person_address add country varchar2(120 char);
alter table erp_person_address add foreign_address boolean;
alter table erp_person_address modify postal_code null;

create table erp_person_phone (
    id number(19,0) generated by default as identity primary key,
    version number(19,0) not null,
    created_at timestamp(6) not null,
    updated_at timestamp(6) not null,
    person_id number(19,0) not null,
    phone_type varchar2(40 char) not null,
    country_code varchar2(8 char),
    phone_number varchar2(40 char) not null,
    whatsapp boolean not null,
    primary_phone boolean not null
);

create table erp_person_email (
    id number(19,0) generated by default as identity primary key,
    version number(19,0) not null,
    created_at timestamp(6) not null,
    updated_at timestamp(6) not null,
    person_id number(19,0) not null,
    email_type varchar2(40 char) not null,
    email_address varchar2(255 char) not null,
    primary_email boolean not null
);

create table erp_person_contact_type (
    id number(19,0) generated by default as identity primary key,
    version number(19,0) not null,
    created_at timestamp(6) not null,
    updated_at timestamp(6) not null,
    code varchar2(80 char) not null,
    name varchar2(255 char) not null,
    description varchar2(255 char),
    address_enabled boolean not null,
    phone_enabled boolean not null,
    email_enabled boolean not null,
    active boolean not null
);

create unique index uk_person_contact_type_code on erp_person_contact_type (code);

alter table erp_person_address add contact_type_id number(19,0);
alter table erp_person_phone add contact_type_id number(19,0);
alter table erp_person_email add contact_type_id number(19,0);

create table erp_armament_parameter (
    id number(19,0) generated by default as identity primary key,
    version number(19,0) not null,
    created_at timestamp(6) not null,
    updated_at timestamp(6) not null,
    parameter_type varchar2(60 char) not null,
    code varchar2(80 char) not null,
    name varchar2(255 char) not null,
    description varchar2(255 char),
    active boolean not null
);

create unique index uk_armament_parameter_code on erp_armament_parameter (parameter_type, code);
create unique index uk_armament_parameter_name on erp_armament_parameter (parameter_type, name);

alter table erp_firearm_specification add caliber_id number(19,0);

alter table erp_ammunition_specification add caliber_id number(19,0);
alter table erp_ammunition_specification add ammunition_type_id number(19,0);
alter table erp_ammunition_specification add projectile_type_id number(19,0);
alter table erp_ammunition_specification add case_type_id number(19,0);
alter table erp_ammunition_specification add primer_type_id number(19,0);

alter table erp_grenade_specification add grenade_type_id number(19,0);
alter table erp_grenade_specification add agent_id number(19,0);
alter table erp_grenade_specification add composition_id number(19,0);

alter table erp_spray_specification add agent_id number(19,0);
alter table erp_spray_specification add composition_id number(19,0);

alter table erp_ballistic_protection_specification add protection_type_id number(19,0);
alter table erp_ballistic_protection_specification add protection_level_id number(19,0);
alter table erp_ballistic_protection_specification add material_id number(19,0);
alter table erp_ballistic_protection_specification add size_id number(19,0);

alter table erp_electrical_device_specification add cartridge_type_id number(19,0);
alter table erp_optical_specification add optical_type_id number(19,0);

alter table erp_helmet_specification add protection_level_id number(19,0);
alter table erp_helmet_specification add material_id number(19,0);
alter table erp_helmet_specification add size_id number(19,0);

alter table erp_shield_specification add shield_type_id number(19,0);
alter table erp_shield_specification add protection_level_id number(19,0);
alter table erp_shield_specification add material_id number(19,0);

alter table erp_restraint_specification add material_id number(19,0);
alter table erp_restraint_specification add locking_mechanism_id number(19,0);

alter table erp_accessory_component_specification add component_type_id number(19,0);
alter table erp_accessory_component_specification add compatibility_id number(19,0);
alter table erp_accessory_component_specification add interface_id number(19,0);

alter table erp_tactical_equipment_specification add material_id number(19,0);
alter table erp_tactical_equipment_specification add size_id number(19,0);


-- Durable legacy -> canonical master-data crosswalk used during Faria Miguel cutover.
create table erp_master_data_reference (
    id number(19,0) generated by default as identity primary key,
    version number(19,0) not null,
    created_at timestamp(6) not null,
    updated_at timestamp(6) not null,
    resource_type varchar2(40 char) not null,
    legacy_id number(19,0) not null,
    canonical_id varchar2(128 char) not null,
    canonical_tenant_id varchar2(128 char) default 'comandos' not null,
    active boolean default true not null,
    last_synchronized_at timestamp(6) not null,
    migration_note varchar2(500 char)
);

create unique index uk_master_data_reference_legacy
    on erp_master_data_reference (resource_type, legacy_id);

create unique index uk_master_data_reference_canonical
    on erp_master_data_reference (resource_type, canonical_id);

create index ix_master_data_reference_active
    on erp_master_data_reference (resource_type, active, legacy_id);


-- Canonical master-data shadow references for product-domain cutover.
alter table erp_stock_location add organization_canonical_id varchar2(128 char);
alter table erp_stock_location add unit_canonical_id varchar2(128 char);

create index ix_stock_location_org_canonical
    on erp_stock_location (organization_canonical_id);

create index ix_stock_location_unit_canonical
    on erp_stock_location (unit_canonical_id);

alter table erp_equipment_set add organization_canonical_id varchar2(128 char);
alter table erp_equipment_set add unit_canonical_id varchar2(128 char);
create index ix_equipment_set_org_canonical
    on erp_equipment_set (organization_canonical_id);
create index ix_equipment_set_unit_canonical
    on erp_equipment_set (unit_canonical_id);

alter table erp_equipment_set_operation add organization_canonical_id varchar2(128 char);
alter table erp_equipment_set_operation add unit_canonical_id varchar2(128 char);
create index ix_equipment_set_operation_org_canonical
    on erp_equipment_set_operation (organization_canonical_id);
create index ix_equipment_set_operation_unit_canonical
    on erp_equipment_set_operation (unit_canonical_id);

alter table erp_certification_record add organization_canonical_id varchar2(128 char);
alter table erp_certification_record add unit_canonical_id varchar2(128 char);
create index ix_certification_record_org_canonical
    on erp_certification_record (organization_canonical_id);
create index ix_certification_record_unit_canonical
    on erp_certification_record (unit_canonical_id);

alter table erp_expiration_record add organization_canonical_id varchar2(128 char);
alter table erp_expiration_record add unit_canonical_id varchar2(128 char);
create index ix_expiration_record_org_canonical
    on erp_expiration_record (organization_canonical_id);
create index ix_expiration_record_unit_canonical
    on erp_expiration_record (unit_canonical_id);

alter table erp_recall add organization_canonical_id varchar2(128 char);
alter table erp_recall add unit_canonical_id varchar2(128 char);
create index ix_recall_org_canonical
    on erp_recall (organization_canonical_id);
create index ix_recall_unit_canonical
    on erp_recall (unit_canonical_id);

alter table erp_custody_responsibility add responsible_person_canonical_id varchar2(128 char);
create index ix_custody_resp_person_canonical
    on erp_custody_responsibility (responsible_person_canonical_id);


-- Canonical master-data shadow references for purchase and receiving cutover.
alter table erp_purchase add buyer_organization_canonical_id varchar2(128 char);
alter table erp_purchase add supplier_organization_canonical_id varchar2(128 char);
alter table erp_purchase add origin_person_canonical_id varchar2(128 char);

create index ix_purchase_buyer_org_canonical
    on erp_purchase (buyer_organization_canonical_id);

create index ix_purchase_supplier_org_canonical
    on erp_purchase (supplier_organization_canonical_id);

create index ix_purchase_origin_person_canonical
    on erp_purchase (origin_person_canonical_id);

alter table erp_procurement_process add organization_canonical_id varchar2(128 char);
create index ix_procurement_process_org_canonical
    on erp_procurement_process (organization_canonical_id);

alter table erp_equipment_receiving add receiving_organization_canonical_id varchar2(128 char);
alter table erp_equipment_receiving add receiving_organization_name varchar2(255 char);

create index ix_equipment_receiving_org_canonical
    on erp_equipment_receiving (receiving_organization_canonical_id);


-- Canonical master-data shadow references for inventory transfer cutover.
alter table erp_inventory_transfer add organization_canonical_id varchar2(128 char);
alter table erp_inventory_transfer add source_unit_canonical_id varchar2(128 char);
alter table erp_inventory_transfer add destination_unit_canonical_id varchar2(128 char);

create index ix_inventory_transfer_org_canonical
    on erp_inventory_transfer (organization_canonical_id);

create index ix_inventory_transfer_source_unit_canonical
    on erp_inventory_transfer (source_unit_canonical_id);

create index ix_inventory_transfer_destination_unit_canonical
    on erp_inventory_transfer (destination_unit_canonical_id);


-- Canonical master-data shadow references for custody, donation and sales cutover.
alter table erp_custody add organization_canonical_id varchar2(128 char);
alter table erp_custody add unit_canonical_id varchar2(128 char);
alter table erp_custody add recipient_canonical_id varchar2(128 char);
alter table erp_custody add recipient_unit_canonical_id varchar2(128 char);
alter table erp_custody add authorizer_canonical_id varchar2(128 char);

create index ix_custody_org_canonical on erp_custody (organization_canonical_id);
create index ix_custody_unit_canonical on erp_custody (unit_canonical_id);
create index ix_custody_recipient_canonical on erp_custody (recipient_canonical_id);
create index ix_custody_recipient_unit_canonical on erp_custody (recipient_unit_canonical_id);
create index ix_custody_authorizer_canonical on erp_custody (authorizer_canonical_id);

alter table erp_donation add organization_canonical_id varchar2(128 char);
alter table erp_donation add unit_canonical_id varchar2(128 char);
alter table erp_donation add donor_canonical_id varchar2(128 char);
alter table erp_donation add donee_canonical_id varchar2(128 char);

create index ix_donation_org_canonical on erp_donation (organization_canonical_id);
create index ix_donation_unit_canonical on erp_donation (unit_canonical_id);
create index ix_donation_donor_canonical on erp_donation (donor_canonical_id);
create index ix_donation_donee_canonical on erp_donation (donee_canonical_id);

alter table erp_sale add organization_canonical_id varchar2(128 char);
alter table erp_sale add unit_canonical_id varchar2(128 char);
alter table erp_sale add buyer_canonical_id varchar2(128 char);

create index ix_sale_org_canonical on erp_sale (organization_canonical_id);
create index ix_sale_unit_canonical on erp_sale (unit_canonical_id);
create index ix_sale_buyer_canonical on erp_sale (buyer_canonical_id);


-- Canonical scope shadow references for maintenance/workflow/disposal/reservation/reconciliation.
alter table erp_work_order add organization_canonical_id varchar2(128 char);
alter table erp_work_order add unit_canonical_id varchar2(128 char);
create index ix_work_order_org_canonical on erp_work_order (organization_canonical_id);
create index ix_work_order_unit_canonical on erp_work_order (unit_canonical_id);

alter table erp_approval_workflow add organization_canonical_id varchar2(128 char);
alter table erp_approval_workflow add unit_canonical_id varchar2(128 char);
create index ix_approval_workflow_org_canonical on erp_approval_workflow (organization_canonical_id);
create index ix_approval_workflow_unit_canonical on erp_approval_workflow (unit_canonical_id);

alter table erp_disposal_process add organization_canonical_id varchar2(128 char);
alter table erp_disposal_process add unit_canonical_id varchar2(128 char);
create index ix_disposal_process_org_canonical on erp_disposal_process (organization_canonical_id);
create index ix_disposal_process_unit_canonical on erp_disposal_process (unit_canonical_id);

alter table erp_inventory_reservation add organization_canonical_id varchar2(128 char);
alter table erp_inventory_reservation add unit_canonical_id varchar2(128 char);
create index ix_inventory_reservation_org_canonical on erp_inventory_reservation (organization_canonical_id);
create index ix_inventory_reservation_unit_canonical on erp_inventory_reservation (unit_canonical_id);

alter table erp_inventory_count add organization_canonical_id varchar2(128 char);
alter table erp_inventory_count add unit_canonical_id varchar2(128 char);
create index ix_inventory_count_org_canonical on erp_inventory_count (organization_canonical_id);
create index ix_inventory_count_unit_canonical on erp_inventory_count (unit_canonical_id);


-- Canonical master-data shadows for consumption, planning and lifecycle cutover.
alter table erp_ammunition_consumption add organization_canonical_id varchar2(128 char);
alter table erp_ammunition_consumption add unit_canonical_id varchar2(128 char);
alter table erp_ammunition_consumption add responsible_canonical_id varchar2(128 char);
alter table erp_ammunition_consumption add authorizer_canonical_id varchar2(128 char);
create index ix_ammunition_consumption_org_canonical on erp_ammunition_consumption (organization_canonical_id);
create index ix_ammunition_consumption_unit_canonical on erp_ammunition_consumption (unit_canonical_id);
create index ix_ammunition_consumption_responsible_canonical on erp_ammunition_consumption (responsible_canonical_id);
create index ix_ammunition_consumption_authorizer_canonical on erp_ammunition_consumption (authorizer_canonical_id);

alter table erp_consumable_usage add organization_canonical_id varchar2(128 char);
alter table erp_consumable_usage add unit_canonical_id varchar2(128 char);
alter table erp_consumable_usage add responsible_canonical_id varchar2(128 char);
alter table erp_consumable_usage add authorizer_canonical_id varchar2(128 char);
create index ix_consumable_usage_org_canonical on erp_consumable_usage (organization_canonical_id);
create index ix_consumable_usage_unit_canonical on erp_consumable_usage (unit_canonical_id);
create index ix_consumable_usage_responsible_canonical on erp_consumable_usage (responsible_canonical_id);
create index ix_consumable_usage_authorizer_canonical on erp_consumable_usage (authorizer_canonical_id);

alter table erp_purchase_planning add organization_canonical_id varchar2(128 char);
create index ix_purchase_planning_org_canonical on erp_purchase_planning (organization_canonical_id);

alter table erp_periodic_inspection add organization_canonical_id varchar2(128 char);
alter table erp_periodic_inspection add unit_canonical_id varchar2(128 char);
create index ix_periodic_inspection_org_canonical on erp_periodic_inspection (organization_canonical_id);
create index ix_periodic_inspection_unit_canonical on erp_periodic_inspection (unit_canonical_id);

alter table erp_exception_occurrence add organization_canonical_id varchar2(128 char);
alter table erp_exception_occurrence add unit_canonical_id varchar2(128 char);
create index ix_exception_occurrence_org_canonical on erp_exception_occurrence (organization_canonical_id);
create index ix_exception_occurrence_unit_canonical on erp_exception_occurrence (unit_canonical_id);
