package com.weaponsregistration.disposal.controller;

import static org.junit.jupiter.api.Assertions.assertEquals;
import java.math.BigDecimal;
import java.net.URI;
import java.net.http.*;
import java.util.*;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.web.server.LocalServerPort;
import org.springframework.jdbc.core.JdbcTemplate;
import tools.jackson.databind.JsonNode;
import tools.jackson.databind.json.JsonMapper;

@SpringBootTest(webEnvironment=SpringBootTest.WebEnvironment.RANDOM_PORT,properties={"spring.datasource.url=jdbc:h2:mem:disposal-tests;MODE=PostgreSQL;DB_CLOSE_DELAY=-1","logging.level.root=WARN","debug=false"})
class DisposalApiTests {
 @LocalServerPort int port;@Autowired JdbcTemplate jdbc;private final HttpClient client=HttpClient.newHttpClient();private final JsonMapper json=JsonMapper.builder().build();record Result(int status,JsonNode body,String raw){}record Setup(long org,long unit,long location,long asset,long lot,long balance){}
 @Test void finalizesDisposalWithDestructionIdempotently()throws Exception{var s=setup();var data=payload(s);var first=request("POST","disposals",data);assertEquals(200,first.status(),first.raw());long id=first.body().get("id").asLong();assertEquals("DISPOSED",jdbc.queryForObject("select status from erp_asset_item where id=?",String.class,s.asset()));assertEquals("7.5000",decimal("select available from erp_stock_balance where id=?",s.balance()));assertEquals("7.5000",decimal("select available_quantity from erp_stock_lot where id=?",s.lot()));assertEquals(2,jdbc.queryForObject("select count(*) from erp_disposal_item where process_id=?",Integer.class,id));assertEquals(1,jdbc.queryForObject("select count(*) from erp_destruction where process_id=?",Integer.class,id));assertEquals(id,request("POST","disposals",data).body().get("id").asLong());assertEquals(1,jdbc.queryForObject("select count(*) from erp_audit_record where resource='disposals' and record_id=?",Integer.class,id));}
 @Test void invalidSecondItemRollsBackEverything()throws Exception{var s=setup();var data=new HashMap<String,Object>(payload(s));data.put("items",List.of(Map.of("assetId",s.asset(),"quantity",1),Map.of("balanceId",s.balance(),"quantity",20)));assertEquals(409,request("POST","disposals",data).status());assertEquals("AVAILABLE",jdbc.queryForObject("select status from erp_asset_item where id=?",String.class,s.asset()));assertEquals("10.0000",decimal("select available from erp_stock_balance where id=?",s.balance()));assertEquals(0,jdbc.queryForObject("select count(*) from erp_disposal_process where request_id=?",Integer.class,data.get("requestId")));assertEquals(0,jdbc.queryForObject("select count(*) from erp_stock_movement where nature='DISPOSAL' and (asset_id=? or lot_id=?)",Integer.class,s.asset(),s.lot()));}
 @Test void validatesDestructionGroupAndExposesHistory()throws Exception{var s=setup();var invalid=new HashMap<String,Object>(payload(s));invalid.remove("destructionCertificate");assertEquals(400,request("POST","disposals",invalid).status());assertEquals(1,request("GET","disposals/stock?organizationId="+s.org()+"&unitId="+s.unit()+"&kind=ASSET",null).body().get("totalElements").asInt());var created=request("POST","disposals",payload(s));assertEquals(200,created.status(),created.raw());assertEquals(1,request("GET","disposals?organizationId="+s.org()+"&unitId="+s.unit(),null).body().get("totalElements").asInt());assertEquals(created.body().get("id").asLong(),request("GET","disposals/"+created.body().get("id").asLong(),null).body().get("id").asLong());}
 private Setup setup()throws Exception{long org=create("core/organizations",Map.of("name",unique(),"nature","Public safety","publicOrganization",true,"active",true));long unit=create("core/units",Map.of("organizationId",org,"code",unique(),"name","Unit","type","Unit"));long category=create("inventory/categories",Map.of("name",unique(),"family","GENERAL","serialized",true,"lotControlled",false,"consumable",false));long lotCategory=create("inventory/categories",Map.of("name",unique(),"family","GENERAL","serialized",false,"lotControlled",true,"consumable",true));long brand=create("inventory/brands",Map.of("name",unique(),"manufacturer","Maker"));long model=create("inventory/models",Map.of("categoryId",category,"brandId",brand,"name","Asset","unitOfMeasure","EA","sku",unique(),"listPrice","10"));long lotModel=create("inventory/models",Map.of("categoryId",lotCategory,"brandId",brand,"name","Supply","unitOfMeasure","EA","sku",unique(),"listPrice","1"));long location=create("inventory/locations",Map.of("organizationId",org,"unitId",unit,"name","Store","type","Controlled","controlled",true));long asset=create("inventory/assets",Map.of("modelId",model,"locationId",location,"assetCode",unique(),"serialNumber",unique(),"condition","DAMAGED","status","AVAILABLE","currentValue","0"));long lot=create("inventory/lots",Map.of("modelId",lotModel,"openingLocationId",location,"lotNumber",unique(),"initialQuantity","10"));long balance=jdbc.queryForObject("select id from erp_stock_balance where lot_id=?",Long.class,lot);return new Setup(org,unit,location,asset,lot,balance);}
 private Map<String,Object> payload(Setup s){return Map.of("requestId",unique(),"organizationId",s.org(),"unitId",s.unit(),"processNumber",unique(),"reason","Unserviceable stock","destructionMethod","Controlled dismantling","destroyedAt","2026-09-11T12:30:00","destructionCertificate","CERT-001","items",List.of(Map.of("assetId",s.asset(),"quantity",1),Map.of("balanceId",s.balance(),"quantity","2.5000")));}
 private Result request(String method,String path,Object body)throws Exception{var req=HttpRequest.newBuilder(URI.create("http://localhost:"+port+"/api/erp/"+path)).header("Content-Type","application/json").method(method,body==null?HttpRequest.BodyPublishers.noBody():HttpRequest.BodyPublishers.ofString(json.writeValueAsString(body))).build();var response=client.send(req,HttpResponse.BodyHandlers.ofString());return new Result(response.statusCode(),response.body().isBlank()?null:json.readTree(response.body()),response.body());}
 private long create(String path,Map<String,Object> body)throws Exception{var result=request("POST",path,body);assertEquals(201,result.status(),result.raw());return result.body().get("id").asLong();}private String decimal(String sql,Object...args){return jdbc.queryForObject(sql,BigDecimal.class,args).setScale(4).toPlainString();}private String unique(){return UUID.randomUUID().toString();}
}
