package com.comandos.donation.controller;
import java.net.URI;import java.net.http.*;import java.util.*;import org.junit.jupiter.api.Test;import org.springframework.beans.factory.annotation.Autowired;import org.springframework.boot.test.context.SpringBootTest;import org.springframework.boot.test.web.server.LocalServerPort;import org.springframework.jdbc.core.JdbcTemplate;import tools.jackson.databind.*;import tools.jackson.databind.json.JsonMapper;import static org.junit.jupiter.api.Assertions.*;
@SpringBootTest(webEnvironment=SpringBootTest.WebEnvironment.RANDOM_PORT,properties={"spring.datasource.url=jdbc:h2:mem:donation-tests;MODE=Oracle;DB_CLOSE_DELAY=-1","logging.level.root=WARN","debug=false"})
class DonationApiTests {
 @LocalServerPort int port;@Autowired JdbcTemplate jdbc;private final HttpClient client=HttpClient.newHttpClient();private final JsonMapper json=JsonMapper.builder().build();record Result(int status,JsonNode body,String raw){}record Setup(long org,long unit,long donor,long donee,long location,long asset,long lot,long balance){}
 private Result request(String method,String path,Object body)throws Exception{var req=HttpRequest.newBuilder(URI.create("http://localhost:"+port+"/api/erp/"+path)).header("Content-Type","application/json").method(method,body==null?HttpRequest.BodyPublishers.noBody():HttpRequest.BodyPublishers.ofString(json.writeValueAsString(body))).build();var res=client.send(req,HttpResponse.BodyHandlers.ofString());return new Result(res.statusCode(),res.body().isBlank()?null:json.readTree(res.body()),res.body());}
 private long create(String path,Map<String,Object> body)throws Exception{var r=request("POST",path,body);assertEquals(201,r.status(),r.raw());return r.body().get("id").asLong();}private String unique(){return UUID.randomUUID().toString();}
 private Setup setup()throws Exception{long org=create("core/organizations",Map.of("name",unique(),"nature","Public safety","publicOrganization",true,"active",true));long unit=create("core/units",Map.of("organizationId",org,"code",unique(),"name","Unit","type","Unit"));long donor=create("core/people",Map.of("personType","INDIVIDUAL","fullName","Donor representative","active",true));long donee=create("core/people",Map.of("personType","LEGAL_ENTITY","fullName","Donee organization","active",true));long category=create("inventory/categories",Map.of("name",unique(),"family","GENERAL","serialized",true,"lotControlled",false,"consumable",false));long lotCategory=create("inventory/categories",Map.of("name",unique(),"family","GENERAL","serialized",false,"lotControlled",true,"consumable",true));long brand=create("inventory/brands",Map.of("name",unique(),"manufacturer","Maker"));long model=create("inventory/models",Map.of("categoryId",category,"brandId",brand,"name","Asset","unitOfMeasure","EA","sku",unique(),"listPrice","10"));long lotModel=create("inventory/models",Map.of("categoryId",lotCategory,"brandId",brand,"name","Supply","unitOfMeasure","EA","sku",unique(),"listPrice","1"));long location=create("inventory/locations",Map.of("organizationId",org,"unitId",unit,"name","Store","type","Controlled","controlled",true));long asset=create("inventory/assets",Map.of("modelId",model,"locationId",location,"assetCode",unique(),"serialNumber",unique(),"condition","GOOD","status","AVAILABLE","currentValue","10"));long lot=create("inventory/lots",Map.of("modelId",lotModel,"openingLocationId",location,"lotNumber",unique(),"initialQuantity","10"));long balance=jdbc.queryForObject("select id from erp_stock_balance where lot_id=?",Long.class,lot);return new Setup(org,unit,donor,donee,location,asset,lot,balance);}
 private Map<String,Object> payload(Setup s){return Map.of("requestId",unique(),"organizationId",s.org(),"unitId",s.unit(),"donorId",s.donor(),"doneeId",s.donee(),"term","DONATION-001","items",List.of(Map.of("assetId",s.asset(),"quantity",1),Map.of("balanceId",s.balance(),"quantity","2.5000")));}
 @Test void finalizesAssetsAndLotsIdempotently()throws Exception{var s=setup();var data=payload(s);var first=request("POST","donations",data);assertEquals(200,first.status(),first.raw());assertEquals("DONATED",jdbc.queryForObject("select status from erp_asset_item where id=?",String.class,s.asset()));
        com.comandos.audit.controller.AuditTraceAssertions.trace(port,"donations",first.body().get("id").asLong(),"assetId="+s.asset()+"&lotId="+s.lot()+"&unitId="+s.unit(),"FINALIZE");assertEquals(0,jdbc.queryForObject("select count(*) from erp_stock_movement where nature='DONATION' and quantity>=0",Integer.class));assertEquals("7.5000",jdbc.queryForObject("select cast(available as varchar) from erp_stock_balance where id=?",String.class,s.balance()));assertEquals(first.body().get("id").asLong(),request("POST","donations",data).body().get("id").asLong());assertEquals(2,jdbc.queryForObject("select count(*) from erp_donation_item where donation_id=?",Integer.class,first.body().get("id").asLong()));assertEquals(1,jdbc.queryForObject("select count(*) from erp_audit_record where resource_name_name='donations' and record_id=?",Integer.class,first.body().get("id").asLong()));}
 @Test void invalidSecondItemRollsBackEverything()throws Exception{var s=setup();var other=setup();var data=new HashMap<String,Object>(payload(s));data.put("items",List.of(Map.of("assetId",s.asset(),"quantity",1),Map.of("balanceId",other.balance(),"quantity",1)));assertEquals(400,request("POST","donations",data).status());assertEquals("AVAILABLE",jdbc.queryForObject("select status from erp_asset_item where id=?",String.class,s.asset()));assertEquals(0,jdbc.queryForObject("select count(*) from erp_donation where request_id=?",Integer.class,data.get("requestId")));}
 @Test void exposesScopedStockAndHistory()throws Exception{var s=setup();assertEquals(1,request("GET","donations/stock?organizationId="+s.org()+"&unitId="+s.unit()+"&kind=ASSET",null).body().get("totalElements").asInt());var created=request("POST","donations",payload(s));assertEquals(200,created.status(),created.raw());assertEquals(0,request("GET","donations/stock?organizationId="+s.org()+"&unitId="+s.unit()+"&kind=ASSET",null).body().get("totalElements").asInt());assertEquals(1,request("GET","donations?organizationId="+s.org()+"&unitId="+s.unit(),null).body().get("totalElements").asInt());assertEquals(created.body().get("id").asLong(),request("GET","donations/"+created.body().get("id").asLong(),null).body().get("id").asLong());}
}
