package com.comandos.lifecycle.service;
import com.comandos.audit.service.AuditService;import com.comandos.core.model.*;import com.comandos.inventory.model.*;
import com.comandos.lifecycle.dto.LifecycleContract.*;import com.comandos.lifecycle.model.*;import com.comandos.maintenance.dto.MaintenanceContract.OpenRequest;
import com.comandos.maintenance.service.MaintenanceService;import com.comandos.security.service.AccessPolicy;import jakarta.persistence.*;import java.math.BigDecimal;import java.time.*;import java.util.*;
import org.springframework.http.*;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import org.springframework.web.server.ResponseStatusException;
@Service@Transactional(readOnly=true)public class LifecycleService{
 private final EntityManager em;private final AccessPolicy access;private final AuditService audit;private final MaintenanceService maintenance;
 public LifecycleService(EntityManager em,AccessPolicy access,AuditService audit,MaintenanceService maintenance){this.em=em;this.access=access;this.audit=audit;this.maintenance=maintenance;}
 @Transactional public InspectionView inspect(InspectionRequest r){if(r==null||r.organizationId()==null||r.assetId()==null||blank(r.checklist())||blank(r.result()))bad("Organization, asset, checklist and result are required.");access.requireScope("inventory/assets","UPDATE",r.organizationId(),r.unitId());var a=locked(AssetItem.class,r.assetId());requireNotDisposed(a);scope(a.location,r.organizationId(),r.unitId());var x=new PeriodicInspection();x.organization=locked(Organization.class,r.organizationId());x.unit=unit(r.organizationId(),r.unitId());x.asset=a;x.checklist=r.checklist().trim();x.result=r.result().trim().toUpperCase(Locale.ROOT);if(!Set.of("APPROVED","FAILED","REPROVED","MAINTENANCE_REQUIRED").contains(x.result))bad("Invalid inspection result.");if(!Set.of("AVAILABLE","BLOCKED").contains(a.status))throw new ResponseStatusException(HttpStatus.CONFLICT,"Asset is not eligible for periodic inspection.");x.damages=clean(r.damages());x.inspectedAt=LocalDateTime.now();var actor=audit.actor();x.responsibleId=actor.id();x.responsibleLogin=actor.login();em.persist(x);if(Set.of("FAILED","REPROVED","MAINTENANCE_REQUIRED").contains(x.result)){a.status="BLOCKED";if(Boolean.TRUE.equals(r.generateMaintenance())){var w=maintenance.open(new OpenRequest(UUID.randomUUID().toString(),r.organizationId(),r.unitId(),null,a.id,"Periodic inspection: "+(x.damages==null?x.result:x.damages),null,"CORRECTIVE",null,null));x.generatedWorkOrderId=w.id();}}em.flush();var v=inspection(x);audit.record("periodic-inspections",x.id,"CREATE",null,v);return v;}
 @Transactional public InspectionView approve(long id){var x=locked(PeriodicInspection.class,id);access.requireScope("inventory/assets","UPDATE",x.organization.id,x.unit==null?null:x.unit.id);if(x.approvedAt!=null)return inspection(x);var actor=audit.actor();x.approvedById=actor.id();x.approvedByLogin=actor.login();x.approvedAt=LocalDateTime.now();audit.record("periodic-inspections",x.id,"APPROVE",null,inspection(x));return inspection(x);}
 public Page<InspectionView> inspections(long org,Long unit,int page){access.requireScope("inventory/assets","READ",org,unit);String w=" where x.organization.id=:o"+(unit==null?"":" and x.unit.id=:u");var q=em.createQuery("select x from PeriodicInspection x"+w+" order by x.id desc",PeriodicInspection.class);var c=em.createQuery("select count(x) from PeriodicInspection x"+w,Long.class);q.setParameter("o",org);c.setParameter("o",org);if(unit!=null){q.setParameter("u",unit);c.setParameter("u",unit);}return new Page<>(q.setFirstResult(page*20).setMaxResults(20).getResultList().stream().map(this::inspection).toList(),c.getSingleResult(),page,20);}
 @Transactional public OccurrenceView occur(OccurrenceRequest r){if(r==null||r.organizationId()==null||blank(r.type())||blank(r.description())||(r.assetId()==null&&r.lotId()==null))bad("Organization, type, description and asset or lot are required.");access.requireScope("inventory/assets","UPDATE",r.organizationId(),r.unitId());var x=new ExceptionOccurrence();x.organization=locked(Organization.class,r.organizationId());x.unit=unit(r.organizationId(),r.unitId());x.type=r.type().trim().toUpperCase(Locale.ROOT);x.description=r.description().trim();x.investigation=clean(r.investigation());x.documentReference=clean(r.documentReference());x.quantity=r.quantity();x.occurredAt=LocalDateTime.now();var actor=audit.actor();x.responsibleId=actor.id();x.responsibleLogin=actor.login();if(r.assetId()!=null){x.asset=locked(AssetItem.class,r.assetId());requireNotDisposed(x.asset);scope(x.asset.location,r.organizationId(),r.unitId());if(Set.of("LOSS","LOST","THEFT","ROBBERY").contains(x.type))x.asset.status="MISSING";else if(Set.of("SEIZURE","DAMAGE","ACCIDENT","RECALL","BLOCK").contains(x.type))x.asset.status="BLOCKED";}else{x.lot=locked(StockLot.class,r.lotId());if(r.balanceId()!=null)x.balance=locked(StockBalance.class,r.balanceId());if(Set.of("SEIZURE","DAMAGE","RECALL","BLOCK").contains(x.type))x.lot.status="BLOCKED";}em.persist(x);em.flush();var v=occurrence(x);audit.record("exception-occurrences",x.id,"CREATE",null,v);return v;}
 @Transactional public OccurrenceView resolve(long id,ResolveRequest r){var x=locked(ExceptionOccurrence.class,id);access.requireScope("inventory/assets","UPDATE",x.organization.id,x.unit==null?null:x.unit.id);if("RESOLVED".equals(x.status))return occurrence(x);if(x.asset!=null)requireNotDisposed(locked(AssetItem.class,x.asset.id));x.status="RESOLVED";x.investigation=clean(r==null?null:r.investigation());x.documentReference=clean(r==null?null:r.documentReference());x.resolvedAt=LocalDateTime.now();var actor=audit.actor();x.resolvedById=actor.id();x.resolvedByLogin=actor.login();if(x.asset!=null&&Set.of("RECOVERY","RECOVERED").contains(x.type))x.asset.status="AVAILABLE";em.flush();var v=occurrence(x);audit.record("exception-occurrences",x.id,"RESOLVE",null,v);return v;}
 public Page<OccurrenceView> occurrences(long org,Long unit,int page){access.requireScope("inventory/assets","READ",org,unit);String w=" where x.organization.id=:o"+(unit==null?"":" and x.unit.id=:u");var q=em.createQuery("select x from ExceptionOccurrence x"+w+" order by x.id desc",ExceptionOccurrence.class);var c=em.createQuery("select count(x) from ExceptionOccurrence x"+w,Long.class);q.setParameter("o",org);c.setParameter("o",org);if(unit!=null){q.setParameter("u",unit);c.setParameter("u",unit);}return new Page<>(q.setFirstResult(page*20).setMaxResults(20).getResultList().stream().map(this::occurrence).toList(),c.getSingleResult(),page,20);}
 @Transactional public AttachmentView attach(AttachmentRequest r){if(r==null||blank(r.resource())||r.recordId()==null||blank(r.fileName())||blank(r.contentType())||blank(r.base64()))bad("Resource, record, file name, content type and file are required.");attachmentScope(r.resource().trim(),r.recordId(),"UPDATE");byte[] data;try{data=Base64.getDecoder().decode(r.base64());}catch(IllegalArgumentException e){bad("Invalid Base64 file.");return null;}if(data.length>10*1024*1024)bad("Attachment exceeds 10 MB.");var a=new OperationAttachment();a.resource=r.resource().trim();a.recordId=r.recordId();a.fileName=r.fileName().trim();a.contentType=r.contentType().trim();a.content=data;a.description=clean(r.description());a.uploadedAt=LocalDateTime.now();var actor=audit.actor();a.uploadedById=actor.id();a.uploadedByLogin=actor.login();em.persist(a);em.flush();var v=attachment(a);audit.record("operation-attachments",a.id,"CREATE",null,v);return v;}
 public List<AttachmentView> attachments(String resource,long recordId){attachmentScope(resource,recordId,"READ");return em.createQuery("select a from OperationAttachment a where a.resource=:r and a.recordId=:id order by a.id",OperationAttachment.class).setParameter("r",resource).setParameter("id",recordId).getResultList().stream().map(this::attachment).toList();}
 public OperationAttachment attachment(long id){var a=em.find(OperationAttachment.class,id);if(a==null)throw new ResponseStatusException(HttpStatus.NOT_FOUND,"Attachment not found.");attachmentScope(a.resource,a.recordId,"READ");return a;}
 private void attachmentScope(String resource,long id,String action){
 switch(resource){
 case "maintenance" -> {var w=em.createQuery("select w from WorkOrder w where w.id=:id",com.comandos.maintenance.model.WorkOrder.class).setParameter("id",id).getResultStream().findFirst().orElse(null);if(w==null)throw new ResponseStatusException(HttpStatus.NOT_FOUND,"Work order not found.");access.requireEntity("maintenance","READ".equals(action)?"READ":"COMPLETE",w);}
 case "periodic-inspections" -> {var x=em.find(PeriodicInspection.class,id);if(x==null)throw new ResponseStatusException(HttpStatus.NOT_FOUND,"Inspection not found.");access.requireScope("inventory/assets",action,x.organization.id,x.unit==null?null:x.unit.id);}
 case "exception-occurrences" -> {var x=em.find(ExceptionOccurrence.class,id);if(x==null)throw new ResponseStatusException(HttpStatus.NOT_FOUND,"Occurrence not found.");access.requireScope("inventory/assets",action,x.organization.id,x.unit==null?null:x.unit.id);}
 case "inventory/assets" -> {var a=em.find(AssetItem.class,id);if(a==null)throw new ResponseStatusException(HttpStatus.NOT_FOUND,"Asset not found.");access.requireEntity(resource,action,a);}
 case "inventory/lots" -> {var a=em.find(StockLot.class,id);if(a==null)throw new ResponseStatusException(HttpStatus.NOT_FOUND,"Lot not found.");access.requireEntity(resource,action,a);}
 default -> bad("Unsupported lifecycle evidence resource.");
 }
 }
 private void requireNotDisposed(AssetItem asset){if("IN_MAINTENANCE".equals(asset.status))throw new ResponseStatusException(HttpStatus.CONFLICT,"Assets in maintenance can only return through work order completion.");if("DISPOSED".equals(asset.status))throw new ResponseStatusException(HttpStatus.CONFLICT,"Disposed assets cannot be reactivated or changed by lifecycle operations.");}
 private InspectionView inspection(PeriodicInspection x){return new InspectionView(x.id,x.asset.id,x.asset.assetCode,x.checklist,x.result,x.damages,x.inspectedAt.toString(),x.responsibleLogin,x.approvedByLogin,x.generatedWorkOrderId);}
 private OccurrenceView occurrence(ExceptionOccurrence x){return new OccurrenceView(x.id,x.type,x.status,x.asset==null?null:x.asset.id,x.lot==null?null:x.lot.id,x.asset!=null?x.asset.assetCode:x.lot.lotNumber,x.quantity,x.description,x.investigation,x.documentReference,x.occurredAt.toString(),x.responsibleLogin,x.resolvedAt==null?null:x.resolvedAt.toString(),x.resolvedByLogin);}
 private AttachmentView attachment(OperationAttachment a){return new AttachmentView(a.id,a.resource,a.recordId,a.fileName,a.contentType,a.description,a.uploadedAt.toString(),a.uploadedByLogin);}
 private OrganizationalUnit unit(long org,Long id){if(id==null)return null;var u=locked(OrganizationalUnit.class,id);if(!u.organization.id.equals(org))bad("Unit does not belong to organization.");return u;}private void scope(StockLocation l,long org,Long unit){if(!l.organization.id.equals(org)||unit!=null&&(l.unit==null||!l.unit.id.equals(unit)))bad("Item is outside selected scope.");}
 private<T>T locked(Class<T>c,long id){T v=em.createQuery("select e from "+c.getSimpleName()+" e where e.id=:id",c).setParameter("id",id).setLockMode(LockModeType.PESSIMISTIC_WRITE).getResultStream().findFirst().orElse(null);if(v==null)throw new ResponseStatusException(HttpStatus.NOT_FOUND,"Record not found.");return v;}private static boolean blank(String s){return s==null||s.isBlank();}private static String clean(String s){return blank(s)?null:s.trim();}private static void bad(String s){throw new ResponseStatusException(HttpStatus.BAD_REQUEST,s);}
}