import type { Metadata } from "next";

import "./globals.css";
import "primeflex/primeflex.css";
import "primeicons/primeicons.css";

import "components/common/loader/loader.css";
import PrimeSSRProvider from "../../prime-ssr-provider";
import { SessionProvider } from "components/auth/session-provider";
import { PreferencesProvider } from "components/settings/preferences-provider";
import { ComandosToaster } from "components/common/toast";

export const metadata: Metadata = {
  title: "Comandos",
  icons: {
    icon: "/comandos-logo-v4.png",
    shortcut: "/comandos-logo-v4.png",
    apple: "/comandos-logo-v4.png"
  },
  description: "Generated by jhfmiguel"
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html
      lang="pt-BR"
      className="h-full antialiased"
    >
      <body className="min-h-full flex flex-col">

        <PrimeSSRProvider>
          <ComandosToaster />
          <PreferencesProvider><SessionProvider>{ children }</SessionProvider></PreferencesProvider>
        </PrimeSSRProvider>

      </body>
    </html>
  );
}
