import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import "./globals.css";
import "bulma/css/bulma.css";

import "components/common/loader/loader.css"

import PrimeSSRProvider from '../../prime-ssr-provider'

// Suppress specific development warnings from console logs on client runtime
if (typeof window !== 'undefined') {
    const originalWarn = console.warn;
    console.warn = (...args) => {
        if (args[0] && String(args[0]).includes('PrimeUI license is malformed')) {
            return;
        }
        originalWarn(...args);
    };
}

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Weapons Registration",
  description: "Generated by jhfmiguel",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        
        {/* Cleaned up erroneous props; license is now handled internally by PrimeSSRProvider */}
        <PrimeSSRProvider>
          {children}
        </PrimeSSRProvider>

      </body>
    </html>
  );
}
