import type { Metadata } from "next";

import "./globals.css";
import "primeflex/primeflex.css";

import "components/common/loader/loader.css";
import PrimeSSRProvider from "../../prime-ssr-provider";
import { SessionProvider } from "components/auth/session-provider";

export const metadata: Metadata = {
  title: "Comandos",
  icons: {
    icon: "/icon.svg"
  },
  description: "Generated by jhfmiguel"
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html
      lang="en"
      className="h-full antialiased"
    >
      <body className="min-h-full flex flex-col">

        <PrimeSSRProvider>
          <SessionProvider>{ children }</SessionProvider>
        </PrimeSSRProvider>

      </body>
    </html>
  );
}
