package com.weaponsregistration.purchase.model;
public enum ReceivingStatus {
    EXPECTED,
    PARTIALLY_RECEIVED,
    RECEIVED,
    UNDER_INSPECTION,
    PROVISIONALLY_ACCEPTED,
    PROVISIONALLY_PARTIALLY_ACCEPTED,
    DEFINITIVELY_ACCEPTED,
    DEFINITIVELY_PARTIALLY_ACCEPTED,
    PARTIALLY_REJECTED,
    REJECTED,
    CANCELLED
}
