package com.comandos.purchase.model;
public enum AcquisitionDocumentType {
    PROCUREMENT_PROCESS, BIDDING_NOTICE, DIRECT_CONTRACTING_ACT,
    CONTRACT, BUDGET_COMMITMENT, PURCHASE_ORDER, INVOICE,
    FREE_ACQUISITION_TERM, DONATION_TERM, TRANSFER_TERM,
    AUTHORIZATION, DELIVERY_DOCUMENT, OTHER
}