package com.comandos.maintenance.controller;import static org.junit.jupiter.api.Assertions.assertEquals;import java.net.*;import java.net.http.*;import java.util.*;import org.junit.jupiter.api.Test;import org.springframework.beans.factory.annotation.Autowired;import org.springframework.boot.test.context.SpringBootTest;import org.springframework.boot.test.web.server.LocalServerPort;import org.springframework.jdbc.core.JdbcTemplate;import tools.jackson.databind.*;import tools.jackson.databind.json.JsonMapper;
@SpringBootTest(webEnvironment=SpringBootTest.WebEnvironment.RANDOM_PORT,properties={"spring.datasource.url=jdbc:h2:mem:maintenance-tests;MODE=PostgreSQL;DB_CLOSE_DELAY=-1","logging.level.root=WARN","debug=false"})class MaintenanceApiTests{
 @LocalServerPort int port;@Autowired JdbcTemplate jdbc;final HttpClient client=HttpClient.newHttpClient();final JsonMapper json=JsonMapper.builder().build();record R(int status,JsonNode body,String raw){}record S(long org,long unit,long asset){}
 @Test void completesApprovedMaintenanceAndPreservesHistory()throws Exception{var s=setup();long plan=create("maintenance/plans",Map.of("organizationId",s.org(),"unitId",s.unit(),"name","Semiannual inspection","type","INSPECTION","periodicityDays",180,"active",true));var opened=request("POST","maintenance/orders",Map.of("requestId",uuid(),"organizationId",s.org(),"unitId",s.unit(),"planId",plan,"assetId",s.asset(),"reason","Scheduled inspection"));assertEquals(200,opened.status(),opened.raw());long id=opened.body().get("id").asLong();assertEquals("IN_MAINTENANCE",status(s.asset()));var completed=request("POST","maintenance/orders/"+id+"/complete",Map.of("requestId",uuid(),"defect","No defect","cause","Scheduled cycle","opinion","Fit for service","services",List.of(Map.of("description","Cleaned and lubricated","cost","25.5000")),"testResult","APPROVED","testNotes","All functions passed"));assertEquals(200,completed.status(),completed.raw());assertEquals("AVAILABLE",status(s.asset()));
        com.comandos.audit.controller.AuditTraceAssertions.trace(port,"maintenance",id,"assetId="+s.asset()+"&unitId="+s.unit(),"OPEN","COMPLETE");assertEquals(1,jdbc.queryForObject("select count(*) from erp_maintenance_diagnosis where work_order_id=?",Integer.class,id));assertEquals(1,jdbc.queryForObject("select count(*) from erp_executed_service where work_order_id=?",Integer.class,id));assertEquals(1,jdbc.queryForObject("select count(*) from erp_functional_test where work_order_id=?",Integer.class,id));assertEquals(2,jdbc.queryForObject("select count(*) from erp_stock_movement where asset_id=? and nature like 'MAINTENANCE_%'",Integer.class,s.asset()));assertEquals(1,request("GET","maintenance/orders?organizationId="+s.org()+"&unitId="+s.unit(),null).body().get("totalElements").asInt());}
 @Test void rejectedTestBlocksAssetAndOpeningIsIdempotent()throws Exception{var s=setup();var payload=Map.of("requestId",uuid(),"organizationId",s.org(),"unitId",s.unit(),"assetId",s.asset(),"reason","Corrective repair");var first=request("POST","maintenance/orders",payload);var second=request("POST","maintenance/orders",payload);assertEquals(first.body().get("id").asLong(),second.body().get("id").asLong());long id=first.body().get("id").asLong();var done=request("POST","maintenance/orders/"+id+"/complete",Map.of("requestId",uuid(),"defect","Feed failure","cause","Worn component","opinion","Keep blocked","services",List.of(Map.of("description","Inspected mechanism","cost",0)),"testResult","REJECTED","testNotes","Failure persists"));assertEquals(200,done.status(),done.raw());assertEquals("BLOCKED",status(s.asset()));assertEquals(1,jdbc.queryForObject("select count(*) from erp_work_order where asset_id=?",Integer.class,s.asset()));}

 @Test void partsScheduleAndRetryPayloadArePreserved() throws Exception {
  var s=setup();
  var opening=new HashMap<String,Object>(Map.of("requestId",uuid(),"organizationId",s.org(),"unitId",s.unit(),"assetId",s.asset(),"reason","Repair","workshop","Workshop A"));
  var opened=request("POST","maintenance/orders",opening);assertEquals(200,opened.status(),opened.raw());long id=opened.body().get("id").asLong();
  opening.put("workshop","Workshop B");assertEquals(409,request("POST","maintenance/orders",opening).status());
  var done=new HashMap<String,Object>(Map.of("requestId",uuid(),"defect","Wear","cause","Use","opinion","Inspected","services",List.of(Map.of("description","Inspection","cost","25.5")),"testResult","APPROVED","testNotes","Passed","parts",List.of(Map.of("description","Replacement","quantity","2","unitCost","3.25","partNumber","P-1")),"nextMaintenanceDays",30));
  var complete=request("POST","maintenance/orders/"+id+"/complete",done);assertEquals(200,complete.status(),complete.raw());assertEquals("32.0000",complete.body().get("totalCost").asText());assertEquals("P-1",complete.body().get("parts").get(0).get("partNumber").asText());
  assertEquals(complete.body(),request("POST","maintenance/orders/"+id+"/complete",done).body());
  done.put("nextMaintenanceDays",31);assertEquals(409,request("POST","maintenance/orders/"+id+"/complete",done).status());done.put("nextMaintenanceDays",30);done.put("parts",List.of());assertEquals(409,request("POST","maintenance/orders/"+id+"/complete",done).status());
  assertEquals(2,jdbc.queryForObject("select count(*) from erp_stock_movement where asset_id=? and nature like 'MAINTENANCE_%'",Integer.class,s.asset()));
 }
 @Test void invalidScheduleRollsBackCompletion() throws Exception {
  var s=setup();var opened=request("POST","maintenance/orders",Map.of("requestId",uuid(),"organizationId",s.org(),"unitId",s.unit(),"assetId",s.asset(),"reason","Repair"));long id=opened.body().get("id").asLong();
  assertEquals(400,request("POST","maintenance/orders/"+id+"/complete",Map.of("requestId",uuid(),"defect","Wear","cause","Use","opinion","Inspect","services",List.of(Map.of("description","Inspect","cost",0)),"testResult","APPROVED","testNotes","Passed","nextMaintenanceDays",-1)).status());
  assertEquals("IN_MAINTENANCE",status(s.asset()));assertEquals(0,jdbc.queryForObject("select count(*) from erp_functional_test where work_order_id=?",Integer.class,id));
 }
 private S setup()throws Exception{long o=create("core/organizations",Map.of("name",uuid(),"nature","Public safety","publicOrganization",true,"active",true)),u=create("core/units",Map.of("organizationId",o,"code",uuid(),"name","Armory","type","Unit")),c=create("inventory/categories",Map.of("name",uuid(),"family","FIREARM","serialized",true,"lotControlled",false,"consumable",false)),b=create("inventory/brands",Map.of("name",uuid(),"manufacturer","Maker")),m=create("inventory/models",Map.of("categoryId",c,"brandId",b,"name","Service pistol","unitOfMeasure","EA","sku",uuid(),"listPrice","1000")),l=create("inventory/locations",Map.of("organizationId",o,"unitId",u,"name","Vault","type","Controlled","controlled",true)),a=create("inventory/assets",Map.of("modelId",m,"locationId",l,"assetCode",uuid(),"serialNumber",uuid(),"condition","GOOD","status","AVAILABLE","currentValue","900"));return new S(o,u,a);}
 private String status(long id){return jdbc.queryForObject("select status from erp_asset_item where id=?",String.class,id);}private long create(String p,Object b)throws Exception{var r=request("POST",p,b);assertEquals(201,r.status(),r.raw());return r.body().get("id").asLong();}private R request(String m,String p,Object b)throws Exception{var q=HttpRequest.newBuilder(URI.create("http://localhost:"+port+"/api/erp/"+p)).header("Content-Type","application/json").method(m,b==null?HttpRequest.BodyPublishers.noBody():HttpRequest.BodyPublishers.ofString(json.writeValueAsString(b))).build();var x=client.send(q,HttpResponse.BodyHandlers.ofString());return new R(x.statusCode(),x.body().isBlank()?null:json.readTree(x.body()),x.body());}private String uuid(){return UUID.randomUUID().toString();}
}
