package com.comandos.lifecycle.dto;
import java.math.BigDecimal;import java.util.List;
public final class LifecycleContract{private LifecycleContract(){}
 public record InspectionItemRequest(Integer order,String code,String label,Boolean required,String result,String observation){}
 public record InspectionItemView(Long id,Integer order,String code,String label,Boolean required,String result,String observation,long photoCount){}
 public record InspectionChecklistRequest(List<InspectionItemRequest> items,Boolean generateMaintenance){}
 public record InspectionRequest(Long organizationId,Long unitId,Long assetId,String checklist,String result,String damages,Boolean generateMaintenance,List<InspectionItemRequest> items){public InspectionRequest(Long organizationId,Long unitId,Long assetId,String checklist,String result,String damages,Boolean generateMaintenance){this(organizationId,unitId,assetId,checklist,result,damages,generateMaintenance,List.of());}}
 public record InspectionView(Long id,Long assetId,String assetCode,String checklist,String result,String damages,String inspectedAt,String responsibleLogin,String approvedByLogin,Long generatedWorkOrderId,List<InspectionItemView> items,long photoCount){public InspectionView(Long id,Long assetId,String assetCode,String checklist,String result,String damages,String inspectedAt,String responsibleLogin,String approvedByLogin,Long generatedWorkOrderId){this(id,assetId,assetCode,checklist,result,damages,inspectedAt,responsibleLogin,approvedByLogin,generatedWorkOrderId,List.of(),0L);}}
 public record OccurrenceRequest(Long organizationId,Long unitId,Long assetId,Long lotId,Long balanceId,String type,BigDecimal quantity,String description,String investigation,String documentReference,Long relatedOccurrenceId){public OccurrenceRequest(Long organizationId,Long unitId,Long assetId,Long lotId,Long balanceId,String type,BigDecimal quantity,String description,String investigation,String documentReference){this(organizationId,unitId,assetId,lotId,balanceId,type,quantity,description,investigation,documentReference,null);}}
 public record OccurrenceView(Long id,String type,String status,Long assetId,Long lotId,String reference,BigDecimal quantity,String description,String investigation,String documentReference,String occurredAt,String responsibleLogin,String resolvedAt,String resolvedByLogin,Long relatedOccurrenceId,String previousItemStatus,String resultingItemStatus,String investigationStartedAt,String investigatedByLogin){public OccurrenceView(Long id,String type,String status,Long assetId,Long lotId,String reference,BigDecimal quantity,String description,String investigation,String documentReference,String occurredAt,String responsibleLogin,String resolvedAt,String resolvedByLogin){this(id,type,status,assetId,lotId,reference,quantity,description,investigation,documentReference,occurredAt,responsibleLogin,resolvedAt,resolvedByLogin,null,null,null,null,null);}}
 public record ResolveRequest(String investigation,String documentReference){}
 public record AttachmentRequest(String resource,Long recordId,String fileName,String contentType,String base64,String description,Long inspectionItemId){public AttachmentRequest(String resource,Long recordId,String fileName,String contentType,String base64,String description){this(resource,recordId,fileName,contentType,base64,description,null);}}
 public record AttachmentView(Long id,String resource,Long recordId,String fileName,String contentType,String description,String uploadedAt,String uploadedByLogin,Long inspectionItemId){public AttachmentView(Long id,String resource,Long recordId,String fileName,String contentType,String description,String uploadedAt,String uploadedByLogin){this(id,resource,recordId,fileName,contentType,description,uploadedAt,uploadedByLogin,null);}}
 public record Page<T>(List<T> content,long totalElements,int page,int size){}
}
