package com.weaponsregistration.maintenance.controller;import com.weaponsregistration.core.controller.CoreExceptionHandler;import org.springframework.web.bind.annotation.RestControllerAdvice;
@RestControllerAdvice(assignableTypes=MaintenanceController.class)public class MaintenanceExceptionHandler extends CoreExceptionHandler{}
